import { Suspense, lazy } from "react";
import { Route, Routes, useLocation } from "react-router-dom";
import AdminLayout from "./components/AdminLayout";
import Layout from "./components/Layout";
import ProtectedRoute from "./components/ProtectedRoute";
import { PageAnalytics } from "./components/AnalyticsBridge";
import Seo from "./components/Seo";

const Home = lazy(() => import("./pages/Home")); const RoutineBuilder = lazy(() => import("./pages/RoutineBuilder")); const Shop = lazy(() => import("./pages/Shop")); const Offers = lazy(() => import("./pages/Offers")); const ProductDetails = lazy(() => import("./pages/ProductDetails")); const Cart = lazy(() => import("./pages/Cart")); const Wishlist = lazy(() => import("./pages/Wishlist")); const Checkout = lazy(() => import("./pages/Checkout")); const Login = lazy(() => import("./pages/Login")); const Register = lazy(() => import("./pages/Register")); const OrderSuccess = lazy(() => import("./pages/OrderSuccess")); const Orders = lazy(() => import("./pages/Orders")); const OrderDetail = lazy(() => import("./pages/OrderDetail")); const TrackOrder = lazy(() => import("./pages/TrackOrder")); const Account = lazy(() => import("./pages/Account")); const Returns = lazy(() => import("./pages/Returns")); const ReturnRequest = lazy(() => import("./pages/ReturnRequest")); const Invoice = lazy(() => import("./pages/Invoice")); const Policy = lazy(() => import("./pages/Policy")); const About = lazy(() => import("./pages/About")); const Contact = lazy(() => import("./pages/Contact")); const NotFound = lazy(() => import("./pages/NotFound")); const ForgotPassword = lazy(() => import("./pages/ForgotPassword")); const ResetPassword = lazy(() => import("./pages/ResetPassword")); const RecoverCart = lazy(() => import("./pages/RecoverCart"));
const AdminCatalog = lazy(() => import("./pages/admin/AdminCatalog")); const AdminMerchandising = lazy(() => import("./pages/admin/AdminMerchandising")); const AdminReports = lazy(() => import("./pages/admin/AdminReports")); const AdminReviews = lazy(() => import("./pages/admin/AdminReviews")); const AdminCustomers = lazy(() => import("./pages/admin/AdminCustomers")); const AdminInventory = lazy(() => import("./pages/admin/AdminInventory")); const AdminDashboard = lazy(() => import("./pages/admin/AdminDashboard")); const AdminOrders = lazy(() => import("./pages/admin/AdminOrders")); const AdminOrderDetail = lazy(() => import("./pages/admin/AdminOrderDetail")); const AdminPromotions = lazy(() => import("./pages/admin/AdminPromotions")); const AdminReturns = lazy(() => import("./pages/admin/AdminReturns")); const AdminSettings = lazy(() => import("./pages/admin/AdminSettings")); const AdminInvoice = lazy(() => import("./pages/admin/AdminInvoice")); const AdminAudience = lazy(() => import("./pages/admin/AdminAudience"));

function LoadingScreen() { return <div className="route-loading phase18-route-loading" aria-label="Loading page"><span /><i /><i /></div>; }
function RoutePrivacySeo() {
  const { pathname } = useLocation();
  const noindex = ["/admin", "/account", "/cart", "/checkout", "/login", "/register", "/forgot-password", "/reset-password", "/recover-cart", "/wishlist", "/orders", "/returns", "/invoice", "/order-success", "/track-order"].some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`));
  return noindex ? <Seo title="Riseora" noindex /> : null;
}
export default function App() { return <><PageAnalytics /><RoutePrivacySeo /><Suspense fallback={<LoadingScreen />}><Routes><Route element={<Layout />}><Route path="/" element={<Home />} /><Route path="/shop" element={<Shop />} /><Route path="/routine-builder" element={<RoutineBuilder />} /><Route path="/offers" element={<Offers />} /><Route path="/about" element={<About />} /><Route path="/contact" element={<Contact />} /><Route path="/product/:slug" element={<ProductDetails />} /><Route path="/cart" element={<Cart />} /><Route path="/wishlist" element={<Wishlist />} /><Route path="/checkout" element={<Checkout />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/reset-password" element={<ResetPassword />} /><Route path="/recover-cart/:cartToken" element={<RecoverCart />} /><Route path="/order-success/:orderNumber" element={<OrderSuccess />} /><Route path="/orders" element={<ProtectedRoute><Orders /></ProtectedRoute>} /><Route path="/orders/:orderNumber" element={<ProtectedRoute><OrderDetail /></ProtectedRoute>} /><Route path="/track-order" element={<TrackOrder />} /><Route path="/account" element={<ProtectedRoute><Account /></ProtectedRoute>} /><Route path="/returns" element={<ProtectedRoute><Returns /></ProtectedRoute>} /><Route path="/returns/new/:orderNumber" element={<ProtectedRoute><ReturnRequest /></ProtectedRoute>} /><Route path="/invoice/:orderNumber" element={<ProtectedRoute><Invoice /></ProtectedRoute>} /><Route path="/policies/:type" element={<Policy />} /><Route path="*" element={<NotFound />} /></Route><Route path="/admin" element={<ProtectedRoute admin><AdminLayout /></ProtectedRoute>}><Route index element={<AdminDashboard />} /><Route path="catalog" element={<AdminCatalog />} /><Route path="reports" element={<AdminReports />} /><Route path="reviews" element={<AdminReviews />} /><Route path="inventory" element={<AdminInventory />} /><Route path="customers" element={<AdminCustomers />} /><Route path="orders" element={<AdminOrders />} /><Route path="orders/:id" element={<AdminOrderDetail />} /><Route path="promotions" element={<AdminPromotions />} /><Route path="merchandising" element={<AdminMerchandising />} /><Route path="returns" element={<AdminReturns />} /><Route path="audience" element={<AdminAudience />} /><Route path="settings" element={<AdminSettings />} /><Route path="orders/:id/invoice" element={<AdminInvoice />} /></Route></Routes></Suspense></>; }
