import { Suspense } from "react";
import { Route, Routes, useLocation } from "react-router-dom";
import AdminLayout from "./components/AdminLayout";
import Layout from "./components/Layout";
import ProtectedRoute from "./components/ProtectedRoute";
import RoutePerformanceBridge from "./components/RoutePerformanceBridge";
import { PageAnalytics } from "./components/AnalyticsBridge";
import Seo from "./components/Seo";
import { lazyRoute } from "./lib/route-modules";

const CampaignDetails = lazyRoute("CampaignDetails");
const Rewards = lazyRoute("Rewards");
const Refills = lazyRoute("Refills");
const HelpCenter = lazyRoute("HelpCenter");
const Support = lazyRoute("Support");
const SecurityCenter = lazyRoute("SecurityCenter");
const PrivacyCenter = lazyRoute("PrivacyCenter");
const Unsubscribe = lazyRoute("Unsubscribe");
const SharedWishlist = lazyRoute("SharedWishlist");
const Compare = lazyRoute("Compare");
const DealDetails = lazyRoute("DealDetails");
const Notifications = lazyRoute("Notifications");
const Home = lazyRoute("Home");
const RoutineBuilder = lazyRoute("RoutineBuilder");
const Shop = lazyRoute("Shop");
const Offers = lazyRoute("Offers");
const ProductDetails = lazyRoute("ProductDetails");
const Cart = lazyRoute("Cart");
const Wishlist = lazyRoute("Wishlist");
const Checkout = lazyRoute("Checkout");
const Login = lazyRoute("Login");
const Register = lazyRoute("Register");
const OrderSuccess = lazyRoute("OrderSuccess");
const Orders = lazyRoute("Orders");
const OrderDetail = lazyRoute("OrderDetail");
const TrackOrder = lazyRoute("TrackOrder");
const Account = lazyRoute("Account");
const Returns = lazyRoute("Returns");
const ReturnRequest = lazyRoute("ReturnRequest");
const ReturnDetail = lazyRoute("ReturnDetail");
const Invoice = lazyRoute("Invoice");
const CreditNote = lazyRoute("CreditNote");
const Policy = lazyRoute("Policy");
const About = lazyRoute("About");
const Contact = lazyRoute("Contact");
const NotFound = lazyRoute("NotFound");
const ForgotPassword = lazyRoute("ForgotPassword");
const ResetPassword = lazyRoute("ResetPassword");
const RecoverCart = lazyRoute("RecoverCart");
const AdminContentStudio = lazyRoute("AdminContentStudio");
const AdminGrowth = lazyRoute("AdminGrowth");
const AdminSecurity = lazyRoute("AdminSecurity");
const AdminCancellations = lazyRoute("AdminCancellations");
const AdminErpSync = lazyRoute("AdminErpSync");
const AdminRetention = lazyRoute("AdminRetention");
const AdminLifecycle = lazyRoute("AdminLifecycle");
const AdminSystem = lazyRoute("AdminSystem");
const AdminCatalog = lazyRoute("AdminCatalog");
const AdminMerchandising = lazyRoute("AdminMerchandising");
const AdminReports = lazyRoute("AdminReports");
const AdminReviews = lazyRoute("AdminReviews");
const AdminCustomers = lazyRoute("AdminCustomers");
const AdminInventory = lazyRoute("AdminInventory");
const AdminDashboard = lazyRoute("AdminDashboard");
const AdminOrders = lazyRoute("AdminOrders");
const AdminOrderDetail = lazyRoute("AdminOrderDetail");
const AdminPromotions = lazyRoute("AdminPromotions");
const AdminReturns = lazyRoute("AdminReturns");
const AdminSettings = lazyRoute("AdminSettings");
const AdminInvoice = lazyRoute("AdminInvoice");
const AdminAudience = lazyRoute("AdminAudience");
const AdminPayments = lazyRoute("AdminPayments");
const AdminFinance = lazyRoute("AdminFinance");
const AdminCreditNote = lazyRoute("AdminCreditNote");
const AdminFulfilment = lazyRoute("AdminFulfilment");
const AdminRewards = lazyRoute("AdminRewards");
const AdminRefills = lazyRoute("AdminRefills");
const AdminSupport = lazyRoute("AdminSupport");
const AdminCompliance = lazyRoute("AdminCompliance");

function LoadingScreen() { return <div className="route-loading phase18-route-loading" aria-label="Loading page"><span /><i /><i /></div>; }
function RoutePrivacySeo() {
  const { pathname } = useLocation();
  const noindex = ["/admin", "/account", "/cart", "/checkout", "/login", "/register", "/forgot-password", "/reset-password", "/recover-cart", "/wishlist", "/compare", "/notifications", "/rewards", "/refills", "/support", "/security", "/privacy-center", "/unsubscribe", "/orders", "/returns", "/invoice", "/order-success", "/track-order"].some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`));
  return noindex ? <Seo title="Riseora" noindex /> : null;
}
export default function App() { return <><PageAnalytics /><RoutePerformanceBridge /><RoutePrivacySeo /><Suspense fallback={<LoadingScreen />}><Routes><Route element={<Layout />}><Route path="/" element={<Home />} /><Route path="/shop" element={<Shop />} /><Route path="/routine-builder" element={<RoutineBuilder />} /><Route path="/offers" element={<Offers />} /><Route path="/offers/:slug" element={<DealDetails />} /><Route path="/campaigns/:slug" element={<CampaignDetails />} /><Route path="/about" element={<About />} /><Route path="/contact" element={<Contact />} /><Route path="/help" element={<HelpCenter />} /><Route path="/support" element={<ProtectedRoute><Support /></ProtectedRoute>} /><Route path="/support/:ticketNumber" element={<ProtectedRoute><Support /></ProtectedRoute>} /><Route path="/product/:slug" element={<ProductDetails />} /><Route path="/cart" element={<Cart />} /><Route path="/wishlist" element={<Wishlist />} /><Route path="/compare" element={<Compare />} /><Route path="/wishlist/shared/:token" element={<SharedWishlist />} /><Route path="/checkout" element={<Checkout />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/reset-password" element={<ResetPassword />} /><Route path="/unsubscribe" element={<Unsubscribe />} /><Route path="/recover-cart/:cartToken" element={<RecoverCart />} /><Route path="/order-success/:orderNumber" element={<OrderSuccess />} /><Route path="/orders" element={<ProtectedRoute><Orders /></ProtectedRoute>} /><Route path="/orders/:orderNumber" element={<ProtectedRoute><OrderDetail /></ProtectedRoute>} /><Route path="/track-order" element={<TrackOrder />} /><Route path="/account" element={<ProtectedRoute><Account /></ProtectedRoute>} /><Route path="/security" element={<ProtectedRoute><SecurityCenter /></ProtectedRoute>} /><Route path="/privacy-center" element={<ProtectedRoute><PrivacyCenter /></ProtectedRoute>} /><Route path="/notifications" element={<ProtectedRoute><Notifications /></ProtectedRoute>} /><Route path="/rewards" element={<ProtectedRoute><Rewards /></ProtectedRoute>} /><Route path="/refills" element={<ProtectedRoute><Refills /></ProtectedRoute>} /><Route path="/returns" element={<ProtectedRoute><Returns /></ProtectedRoute>} /><Route path="/returns/new/:orderNumber" element={<ProtectedRoute><ReturnRequest /></ProtectedRoute>} /><Route path="/returns/:id" element={<ProtectedRoute><ReturnDetail /></ProtectedRoute>} /><Route path="/invoice/:orderNumber" element={<ProtectedRoute><Invoice /></ProtectedRoute>} /><Route path="/credit-note/:returnNumber" element={<ProtectedRoute><CreditNote /></ProtectedRoute>} /><Route path="/policies/:type" element={<Policy />} /><Route path="*" element={<NotFound />} /></Route><Route path="/admin" element={<ProtectedRoute admin><AdminLayout /></ProtectedRoute>}><Route index element={<AdminDashboard />} /><Route path="catalog" element={<AdminCatalog />} /><Route path="reports" element={<AdminReports />} /><Route path="reviews" element={<AdminReviews />} /><Route path="inventory" element={<AdminInventory />} /><Route path="customers" element={<AdminCustomers />} /><Route path="support" element={<AdminSupport />} /><Route path="orders" element={<AdminOrders />} /><Route path="fulfilment" element={<AdminFulfilment />} /><Route path="payments" element={<AdminPayments />} /><Route path="finance" element={<AdminFinance />} /><Route path="orders/:id" element={<AdminOrderDetail />} /><Route path="promotions" element={<AdminPromotions />} /><Route path="content" element={<AdminContentStudio />} /><Route path="merchandising" element={<AdminMerchandising />} /><Route path="returns" element={<AdminReturns />} /><Route path="cancellations" element={<AdminCancellations />} /><Route path="audience" element={<AdminAudience />} /><Route path="retention" element={<AdminRetention />} /><Route path="lifecycle" element={<AdminLifecycle />} /><Route path="growth" element={<AdminGrowth />} /><Route path="rewards" element={<AdminRewards />} /><Route path="refills" element={<AdminRefills />} /><Route path="settings" element={<AdminSettings />} /><Route path="erp-sync" element={<AdminErpSync />} /><Route path="security" element={<AdminSecurity />} /><Route path="compliance" element={<AdminCompliance />} /><Route path="system" element={<AdminSystem />} /><Route path="orders/:id/invoice" element={<AdminInvoice />} /><Route path="credit-notes/:id" element={<AdminCreditNote />} /></Route></Routes></Suspense></>; }
