ALTER TABLE "StoreSetting" ADD COLUMN IF NOT EXISTS "codEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreSetting" ADD COLUMN IF NOT EXISTS "codMinOrderAmount" DECIMAL(12,2);
ALTER TABLE "StoreSetting" ADD COLUMN IF NOT EXISTS "codMaxOrderAmount" DECIMAL(12,2);
ALTER TABLE "StoreSetting" ADD COLUMN IF NOT EXISTS "maxOpenCodOrdersPerCustomer" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "codAllowed" BOOLEAN NOT NULL DEFAULT true;
