import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../api/http";
import SupportCaseCenter from "../components/SupportCaseCenter";

const money = (value) => `₹${Number(value || 0).toFixed(0)}`;
const terminal = new Set(["REFUNDED", "REPLACED", "REJECTED", "CANCELLED"]);
export default function Returns() {
  const [returns, setReturns] = useState([]); const [error, setError] = useState(""); const [filter, setFilter] = useState("ACTIVE");
  async function load() { const response = await apiFetch("/returns"); setReturns(response.data); }
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  async function cancel(id) { if (!window.confirm("Cancel this return request?")) return; try { await apiFetch(`/returns/${id}/cancel`, { method: "POST" }); await load(); } catch (e) { setError(e.message); } }
  const visible = useMemo(() => returns.filter((item) => filter === "ALL" || (filter === "ACTIVE" ? !terminal.has(item.status) : terminal.has(item.status))), [returns, filter]);
  const active = returns.filter((item) => !terminal.has(item.status)).length, completed = returns.length - active;
  return <div className="container page-space returns-page phase83-returns-page">
    <div className="page-heading-row"><div><p className="eyebrow">PHASE 84 · POST-PURCHASE CARE</p><h1>Returns, replacements & support</h1><p>Track returns and replacements, then continue into customer-care support without losing order context.</p></div><Link className="button button-secondary" to="/orders">My orders</Link></div>
    {error && <p className="alert error">{error}</p>}
    <div className="phase83-return-kpis"><article><span>ACTIVE CASES</span><strong>{active}</strong></article><article><span>COMPLETED</span><strong>{completed}</strong></article><article><span>TOTAL CASES</span><strong>{returns.length}</strong></article></div>
    <div className="phase83-return-tabs">{["ACTIVE","COMPLETED","ALL"].map((value) => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{value}</button>)}</div>
    {visible.length === 0 ? <div className="empty-state"><h2>No returns in this view</h2><p>Eligible delivered orders can start a return from Order Details.</p><Link className="button" to="/orders">View orders</Link></div> : <div className="return-card-list">{visible.map((item) => <article className="return-card phase83-return-card" key={item.id}><div className="return-card-head"><div><small>{item.returnNumber}</small><h2>{item.order.orderNumber}</h2><span>Requested {new Date(item.requestedAt).toLocaleDateString()}</span></div><span className={`return-pill return-${item.status.toLowerCase().replaceAll("_", "-")}`}>{item.status.replaceAll("_", " ")}</span></div><div className="phase83-return-meta"><span><small>REQUESTED</small><strong>{item.preferredResolution === "REPLACEMENT" ? "Replacement" : "Refund"}</strong></span><span><small>APPROVED</small><strong>{item.approvedResolution ? item.approvedResolution.replaceAll("_", " ") : "Under review"}</strong></span><span><small>PRIORITY</small><strong>{item.priority || "NORMAL"}</strong></span></div><div className="return-items-mini">{item.items.map((line) => <span key={line.id}>{line.orderItem.productName} × {line.quantity}</span>)}</div>{item.resolutionHealth?.overdue && <p className="alert warning phase83-inline-alert">This case is past its review SLA. Riseora operations has been flagged.</p>}<div className="return-card-foot"><span>{item.approvedResolution === "REPLACEMENT" ? "Replacement case" : <>Refund ceiling <strong>{money(item.refundAmount)}</strong></>}</span><div className="return-card-actions"><Link className="link-button" to={`/returns/${item.id}`}>View resolution</Link>{item.status === "REQUESTED" && <button className="link-button danger-text" onClick={() => cancel(item.id)}>Cancel request</button>}</div></div>{item.replacementTrackingNumber && <div className="shipment-box"><span>{item.replacementCarrier || "Replacement courier"}</span><strong>{item.replacementTrackingNumber}</strong>{item.replacementTrackingUrl && <a href={item.replacementTrackingUrl} target="_blank" rel="noreferrer">Track replacement ↗</a>}</div>}{item.reverseTrackingNumber && !item.replacementTrackingNumber && <div className="shipment-box"><span>{item.reverseCarrier || "Return courier"}</span><strong>{item.reverseTrackingNumber}</strong>{item.reverseTrackingUrl && <a href={item.reverseTrackingUrl} target="_blank" rel="noreferrer">Track return ↗</a>}</div>}</article>)}</div>}
    <SupportCaseCenter />
  </div>;
}
