import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../../api/http";
import { Icon } from "../../components/Icons";

function money(v) { return Number(v || 0).toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }); }
function when(v) { return v ? new Date(v).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "numeric", minute: "2-digit" }) : "—"; }

export default function AdminPayments() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { const response = await apiFetch("/admin/payments/operations"); setData(response.data); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const sessions = useMemo(() => (data?.sessions || []).filter((s) => !query || `${s.customerName} ${s.customerEmail || ""} ${s.customerPhone || ""} ${s.providerOrderId || ""}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  async function release(id) { if (!window.confirm("Release this pending reservation? Reserved stock and coupon usage will be returned.")) return; setMessage(""); try { const r = await apiFetch(`/admin/payments/checkout-sessions/${id}/release`, { method: "POST" }); setMessage(r.message || "Reservation released"); await load(); } catch (e) { setMessage(e.message); } }
  if (loading && !data) return <div className="admin-page"><p>Loading payment operations…</p></div>;
  const summary = data?.summary || {};
  const readiness = data?.paymentReadiness || {};
  const safety = data?.submissionSafety || {};
  return <div className="admin-page phase33-admin-payments"><div className="admin-page-header"><div><p className="eyebrow">CHECKOUT OPERATIONS</p><h1>Payments</h1><p>Recoverable Razorpay sessions, reserved stock and payment webhook health.</p></div><button className="button button-secondary" onClick={load}><Icon name="refresh" size={17} /> Refresh</button></div>
    {message && <p className="alert">{message}</p>}
    <section className="admin-card phase74-payment-health"><div className="admin-card-head"><div><p className="eyebrow">PHASE 74 · PAYMENT CLARITY</p><h2>Checkout payment readiness</h2><p>Rolling payment-option availability before order/payment submission. These signals are aggregate only.</p></div><span className={readiness.onlineConfigured ? "phase74-provider-state configured" : "phase74-provider-state"}>{readiness.onlineConfigured ? `${readiness.provider || "Online"} configured` : "Online not configured"}</span></div><div className="phase74-payment-health-grid"><article><small>READINESS CHECKS · 60M</small><strong>{readiness.checks || 0}</strong><span>Payment-option previews</span></article><article><small>BOTH READY</small><strong>{readiness.bothAvailable || 0}</strong><span>{Number(readiness.bothAvailableRatePercent || 0).toFixed(1)}% of checks</span></article><article><small>PREPAID-ONLY</small><strong>{readiness.prepaidOnly || 0}</strong><span>{Number(readiness.prepaidOnlyRatePercent || 0).toFixed(1)}% of checks</span></article><article><small>COD-ONLY</small><strong>{readiness.codOnly || 0}</strong><span>Online provider unavailable</span></article><article><small>NO METHOD</small><strong>{readiness.noMethod || 0}</strong><span>Requires configuration/cart action</span></article><article><small>COD BLOCKED</small><strong>{readiness.codBlocked || 0}</strong><span>Any COD restriction</span></article></div>{readiness.note && <p className="phase74-admin-note">{readiness.note}</p>}</section>

    <section className="admin-card phase77-submission-health"><div className="admin-card-head"><div><p className="eyebrow">PHASE 77 · SUBMISSION SAFETY</p><h2>Duplicate & retry protection</h2><p>Rolling idempotency and payment-attempt integrity signals. Aggregate only; no customer/cart/request-key payload is retained.</p></div></div><div className="phase77-submission-health-grid"><article><small>COD REPLAYS · 60M</small><strong>{safety.codReplays || 0}</strong><span>Same protected key returned existing order</span></article><article><small>ONLINE RESUMES · 60M</small><strong>{safety.onlineResumes || 0}</strong><span>Existing reservation safely reused</span></article><article><small>PAYLOAD MISMATCH</small><strong>{safety.payloadMismatches || 0}</strong><span>Changed checkout blocked from key reuse</span></article><article><small>PROVIDER REUSE</small><strong>{safety.providerOrdersReused || 0}</strong><span>Existing Razorpay order reused</span></article><article><small>FINALIZE REPLAYS</small><strong>{safety.finalizationReplays || 0}</strong><span>Duplicate verification returned existing order</span></article><article><small>MISSING KEYS</small><strong>{safety.missingRequestKeys || 0}</strong><span>Mutation requests rejected</span></article></div>{safety.note && <p className="phase74-admin-note">{safety.note}</p>}</section>
    <div className="phase33-payment-stats"><article><small>ACTIVE RESERVATIONS</small><strong>{summary.pending || 0}</strong><span>Stock currently reserved</span></article><article><small>EXPIRED PENDING</small><strong>{summary.expiredPending || 0}</strong><span>Safe to release</span></article><article><small>PAID • 24H</small><strong>{summary.paid24h || 0}</strong><span>Online payments completed</span></article><article><small>WEBHOOKS • 24H</small><strong>{summary.webhook24h || 0}</strong><span>{summary.failedWebhook24h || 0} failed-payment events</span></article></div>
    <section className="admin-card"><div className="admin-card-head"><div><h2>Pending online checkouts</h2><p>A dismissed browser window no longer cancels these automatically. Reservations expire after 30 minutes unless payment completes.</p></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search customer or provider order" /></div>
      <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Amount</th><th>Payment state</th><th>Provider</th><th>Expires</th><th></th></tr></thead><tbody>{sessions.map((s) => <tr key={s.id}><td><strong>{s.customerName}</strong><small>{s.customerEmail || s.customerPhone}</small></td><td>{money(s.totalAmount)}</td><td><span className={`phase33-pay-state ${(s.lastPaymentStatus || "reserved").toLowerCase()}`}>{s.lastPaymentStatus || "RESERVED"}</span><small>{s.lastPaymentError || `${s.paymentAttemptCount || 0} attempt(s)`}</small></td><td><small>{s.providerOrderId || "Provider order pending"}</small><small>{when(s.lastPaymentActivityAt)}</small></td><td><strong>{when(s.expiresAt)}</strong><small>{new Date(s.expiresAt) < new Date() ? "EXPIRED" : "Reserved"}</small></td><td><button className="table-action" disabled={new Date(s.expiresAt) >= new Date()} title={new Date(s.expiresAt) >= new Date() ? "Active reservations cannot be released while a delayed payment may still arrive" : "Release expired reservation"} onClick={() => release(s.id)}>Release</button></td></tr>)}{sessions.length === 0 && <tr><td colSpan="6">No pending payment sessions match this view.</td></tr>}</tbody></table></div>
    </section>
  </div>;
}
