import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../../api/http";

function num(value) { return Number(value || 0).toLocaleString("en-IN"); }
function money(value) { return Number(value || 0).toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }); }
const settingKeys = ["rewardPointsPerHundred","rewardVoucherPoints","rewardVoucherAmount","rewardVoucherMinOrderAmount","rewardVoucherValidityDays","rewardReviewBonusPoints","rewardReferralReferrerPoints","rewardReferralNewCustomerPoints"];

export default function AdminRewards() {
  const [data,setData]=useState(null); const [settings,setSettings]=useState(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [adjust,setAdjust]=useState({userId:"",points:"",reason:""});
  async function load(){const r=await apiFetch("/admin/rewards");setData(r.data);const s=r.data.settings;setSettings({rewardsEnabled:s.rewardsEnabled,...Object.fromEntries(settingKeys.map((k)=>[k,String(Number(s[k]||0))]))});}
  useEffect(()=>{load().catch((e)=>setError(e.message));},[]);
  async function save(e){e.preventDefault();setError("");setMessage("");try{const payload={rewardsEnabled:settings.rewardsEnabled};for(const key of settingKeys)payload[key]=Number(settings[key]||0);await apiFetch("/admin/rewards/settings",{method:"PATCH",body:JSON.stringify(payload)});setMessage("Rewards settings saved.");await load();}catch(e){setError(e.message);}}
  async function adjustMember(e){e.preventDefault();setError("");setMessage("");try{await apiFetch(`/admin/rewards/members/${adjust.userId}/adjust`,{method:"POST",body:JSON.stringify({points:Number(adjust.points),reason:adjust.reason})});setMessage("Customer points adjusted.");setAdjust({userId:"",points:"",reason:""});await load();}catch(e){setError(e.message);}}
  const selected = useMemo(()=>data?.members?.find((m)=>m.userId===adjust.userId),[data,adjust.userId]);
  if(!data||!settings)return <div className="admin-empty">Loading rewards…</div>;
  const m=data.metrics;
  return <><div className="admin-page-heading"><div><p className="eyebrow">RETENTION ENGINE</p><h1>Rewards & referrals</h1><p>Control earn rates, private reward vouchers, referral bonuses and customer point balances.</p></div></div>{message&&<p className="alert success">{message}</p>}{error&&<p className="alert error">{error}</p>}
  <div className="phase36-admin-kpis"><article><small>REWARD MEMBERS</small><strong>{num(m.members)}</strong></article><article><small>POINTS OUTSTANDING</small><strong>{num(m.totalOutstanding)}</strong></article><article><small>EARNED · 30D</small><strong>{num(m.earned30d)}</strong></article><article><small>REDEEMED · 30D</small><strong>{num(m.redeemed30d)}</strong></article><article><small>REFERRED ACCOUNTS</small><strong>{num(m.referralCount)}</strong></article><article><small>VOUCHERS USED</small><strong>{num(m.vouchersUsed)} / {num(m.vouchersIssued)}</strong></article></div>
  <div className="phase36-admin-layout"><form className="admin-panel admin-form" onSubmit={save}><div className="admin-panel-head"><div><h2>Program settings</h2><p>These values apply to future reward activity. Existing transactions are never rewritten.</p></div><label className="checkbox-row"><input type="checkbox" checked={settings.rewardsEnabled} onChange={(e)=>setSettings({...settings,rewardsEnabled:e.target.checked})}/> Rewards enabled</label></div>
  <div className="admin-field-grid three"><label>Points per ₹100 spend<input type="number" min="0" max="500" value={settings.rewardPointsPerHundred} onChange={(e)=>setSettings({...settings,rewardPointsPerHundred:e.target.value})}/></label><label>Voucher points cost<input type="number" min="1" value={settings.rewardVoucherPoints} onChange={(e)=>setSettings({...settings,rewardVoucherPoints:e.target.value})}/></label><label>Voucher value ₹<input type="number" min="1" step="0.01" value={settings.rewardVoucherAmount} onChange={(e)=>setSettings({...settings,rewardVoucherAmount:e.target.value})}/></label></div>
  <div className="admin-field-grid three"><label>Voucher minimum order ₹<input type="number" min="0" step="0.01" value={settings.rewardVoucherMinOrderAmount} onChange={(e)=>setSettings({...settings,rewardVoucherMinOrderAmount:e.target.value})}/></label><label>Voucher validity days<input type="number" min="1" max="3650" value={settings.rewardVoucherValidityDays} onChange={(e)=>setSettings({...settings,rewardVoucherValidityDays:e.target.value})}/></label><label>Verified review bonus<input type="number" min="0" value={settings.rewardReviewBonusPoints} onChange={(e)=>setSettings({...settings,rewardReviewBonusPoints:e.target.value})}/></label></div>
  <div className="admin-field-grid two"><label>Referrer bonus points<input type="number" min="0" value={settings.rewardReferralReferrerPoints} onChange={(e)=>setSettings({...settings,rewardReferralReferrerPoints:e.target.value})}/></label><label>New customer referral points<input type="number" min="0" value={settings.rewardReferralNewCustomerPoints} onChange={(e)=>setSettings({...settings,rewardReferralNewCustomerPoints:e.target.value})}/></label></div><button className="button">Save rewards settings</button></form>
  <form className="admin-panel admin-form" onSubmit={adjustMember}><div className="admin-panel-head"><div><h2>Manual point adjustment</h2><p>Use for customer-service corrections. Every adjustment is kept in the reward ledger.</p></div></div><label>Customer<select required value={adjust.userId} onChange={(e)=>setAdjust({...adjust,userId:e.target.value})}><option value="">Choose reward member</option>{data.members.map((row)=><option key={row.userId} value={row.userId}>{row.user.firstName} {row.user.lastName||""} · {row.user.email} · {row.balance} pts</option>)}</select></label>{selected&&<p className="phase36-adjust-balance">Current balance <strong>{selected.balance} pts</strong></p>}<label>Points (+ credit / - debit)<input required type="number" step="1" value={adjust.points} onChange={(e)=>setAdjust({...adjust,points:e.target.value})} placeholder="50 or -25"/></label><label>Reason<input required minLength="3" value={adjust.reason} onChange={(e)=>setAdjust({...adjust,reason:e.target.value})} placeholder="Customer service goodwill"/></label><button className="button button-secondary">Apply adjustment</button></form></div>
  <div className="admin-settings-grid"><section className="admin-panel"><div className="admin-panel-head"><div><h2>Top reward members</h2><p>Highest current balances.</p></div></div><div className="phase36-admin-member-list">{data.members.slice(0,12).map((row)=><div key={row.userId}><span><strong>{row.user.firstName} {row.user.lastName||""}</strong><small>{row.user.email} · {row.user.referralCode}</small></span><b>{num(Math.max(0,row.balance))} pts</b></div>)}</div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Recent rewards activity</h2><p>Latest 50 ledger entries.</p></div></div><div className="phase36-admin-transaction-list">{data.recentTransactions.map((row)=><div key={row.id}><span className={row.points>=0?"positive":"negative"}>{row.points>=0?"+":""}{row.points}</span><p><strong>{row.user?.firstName||"Customer"} · {row.type.replaceAll("_"," ")}</strong><small>{row.description}</small></p><time>{new Date(row.createdAt).toLocaleDateString("en-IN")}</time></div>)}</div></section></div>
  <p className="admin-help-note"><strong>Accounting note:</strong> reward points are a promotional liability, not cash. Before launch, confirm voucher accounting/GST treatment with Riseora's accountant.</p></>;
}
