import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../../api/http";
import { Icon } from "../../components/Icons";

function dateValue(date) { return date.toISOString().slice(0, 10); }
function money(value) { return Number(value || 0).toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }); }
function pct(value) { return `${Number(value || 0).toFixed(2)}%`; }
function csvCell(value) { const text = String(value ?? ""); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }

export default function AdminFinance() {
  const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1);
  const [from, setFrom] = useState(dateValue(first)); const [to, setTo] = useState(dateValue(now));
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [tab, setTab] = useState("overview");
  const query = `from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;
  async function load() { setLoading(true); setError(""); try { const r = await apiFetch(`/admin/finance?${query}`); setData(r.data); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function action(name, path, options = {}) { setWorking(name); setMessage(""); setError(""); try { const r = await apiFetch(`${path}${path.includes("?") ? "&" : "?"}${query}`, { method: "POST", ...options }); setMessage(r.message || "Done"); await load(); } catch (e) { setError(e.message); } finally { setWorking(""); } }
  async function collectCod(row) { const reference = window.prompt(`Collection reference for ${row.orderNumber} (optional)`, `COD-${row.orderNumber}`); if (reference === null) return; await action(`cod-${row.orderId}`, `/admin/finance/cod/${row.orderId}/collect`, { body: JSON.stringify({ reference }) }); }
  const summary = data?.summary || {};
  const reviewRows = useMemo(() => (data?.payments || []).filter((row) => row.reconciliationStatus !== "MATCHED" || (row.method === "COD" && row.orderStatus === "DELIVERED" && row.paymentStatus !== "PAID")), [data]);
  function exportCsv() {
    if (!data) return;
    const rows = [["Finance export", `${from} to ${to}`], [], ["Metric", "Value"], ["Gross order value", summary.grossOrders], ["Collected", summary.collected], ["Refunded", summary.refunded], ["Net collected", summary.netCollected], ["Net taxable", summary.netTaxable], ["Net GST", summary.netTax], [], ["Payments"], ["Order", "Customer", "Method", "Order status", "Payment status", "Amount", "Refunded", "Reconciliation", "Note"]];
    for (const row of data.payments || []) rows.push([row.orderNumber, row.customerName, row.method, row.orderStatus, row.paymentStatus, row.totalAmount, row.refundedAmount, row.reconciliationStatus, row.reconciliationNote || ""]);
    rows.push([], ["GST rates"], ["Rate", "Taxable", "Tax", "Credit taxable", "Credit tax", "Net taxable", "Net tax"]);
    for (const row of data.tax?.rates || []) rows.push([row.rate, row.taxable, row.tax, row.creditTaxable, row.creditTax, row.netTaxable, row.netTax]);
    const csv = rows.map((row) => row.map(csvCell).join(",")).join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `riseora-finance-${from}-${to}.csv`; a.click(); URL.revokeObjectURL(url);
  }
  return <div className="admin-page phase45-finance">
    <div className="admin-page-header"><div><p className="eyebrow">FINANCE CONTROL</p><h1>GST, invoices & reconciliation</h1><p>Tax documents, collections, refunds and payment/order consistency in one operational workspace.</p></div><div className="phase45-finance-head-actions"><button className="button button-secondary" onClick={exportCsv} disabled={!data}>Export CSV</button><button className="button button-secondary" onClick={load}><Icon name="refresh" size={17} /> Refresh</button></div></div>
    {message && <p className="alert">{message}</p>}{error && <p className="alert error">{error}</p>}
    <section className="admin-panel phase45-finance-toolbar"><div className="admin-field-grid two"><label>From<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label></div><button className="button" onClick={load} disabled={loading}>Apply range</button></section>
    {loading && !data ? <p>Loading finance data…</p> : data && <>
      <div className="phase45-finance-kpis"><article><small>GROSS ORDER VALUE</small><strong>{money(summary.grossOrders)}</strong><span>{summary.orders} orders</span></article><article><small>NET COLLECTED</small><strong>{money(summary.netCollected)}</strong><span>{money(summary.refunded)} refunded</span></article><article><small>NET GST</small><strong>{money(summary.netTax)}</strong><span>{money(summary.netTaxable)} taxable</span></article><article><small>DOCUMENT GAPS</small><strong>{summary.missingInvoices || 0}</strong><span>{summary.creditNotes || 0} credit notes issued</span></article><article><small>PAYMENT REVIEW</small><strong>{summary.reconciliationReview || 0}</strong><span>{summary.reconciliationUnchecked || 0} unchecked</span></article><article><small>COD OUTSTANDING</small><strong>{summary.codOutstanding || 0}</strong><span>Delivered, not collected</span></article></div>
      <div className="phase45-finance-tabs">{[["overview","Overview"],["gst","GST summary"],["payments","Reconciliation"],["credits","Credit notes"],["qa","Tax QA"]].map(([key,label]) => <button key={key} className={tab===key?"active":""} onClick={() => setTab(key)}>{label}</button>)}</div>
      {tab === "overview" && <div className="phase45-finance-grid">
        <section className="admin-panel"><div className="admin-panel-head"><div><h2>Document readiness</h2><p>Issue missing documents explicitly; viewing this page never consumes invoice numbers.</p></div></div><div className="phase45-finance-actions"><button className="button" disabled={working==="invoice" || !summary.missingInvoices} onClick={() => action("invoice", "/admin/finance/invoices/issue-missing")}>{working==="invoice"?"Issuing…":`Issue ${summary.missingInvoices || 0} missing invoice(s)`}</button><button className="button button-secondary" disabled={working==="credit"} onClick={() => action("credit", "/admin/finance/credit-notes/issue-missing")}>{working==="credit"?"Checking…":"Issue missing refund credit notes"}</button></div>{(data.missingInvoices || []).slice(0,8).map((row) => <div className="phase45-finance-line" key={row.id}><span><strong>{row.orderNumber}</strong><small>{row.customerName} · {row.status}</small></span><b>{money(row.totalAmount)}</b></div>)}</section>
        <section className="admin-panel"><div className="admin-panel-head"><div><h2>Business tax setup</h2><p>Production tax documents depend on these settings.</p></div><Link to="/admin/settings">Edit settings →</Link></div><div className="phase45-tax-setup"><span className={data.setup.gstin?"ok":"warn"}><b>GSTIN</b>{data.setup.gstin || "Missing"}</span><span className={data.setup.pan?"ok":"warn"}><b>PAN</b>{data.setup.pan || "Missing"}</span><span className={data.setup.state?"ok":"warn"}><b>Seller state</b>{data.setup.state || "Missing"}</span><span className="ok"><b>Invoice series</b>{data.setup.invoicePrefix}</span><span className="ok"><b>Credit-note series</b>{data.setup.creditNotePrefix}</span></div></section>
      </div>}
      {tab === "gst" && <><div className="phase45-gst-kpis"><article><span>Taxable value</span><strong>{money(summary.netTaxable)}</strong></article><article><span>CGST</span><strong>{money(summary.netCgst)}</strong></article><article><span>SGST</span><strong>{money(summary.netSgst)}</strong></article><article><span>IGST</span><strong>{money(summary.netIgst)}</strong></article><article><span>Net GST</span><strong>{money(summary.netTax)}</strong></article></div><section className="admin-panel"><div className="admin-panel-head"><div><h2>GST rate summary</h2><p>Issued invoices less issued credit notes within the selected period.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>GST rate</th><th>Invoice taxable</th><th>Invoice tax</th><th>Credit taxable</th><th>Credit tax</th><th>Net taxable</th><th>Net tax</th></tr></thead><tbody>{(data.tax?.rates || []).map((row) => <tr key={row.rate}><td><strong>{pct(row.rate)}</strong></td><td>{money(row.taxable)}</td><td>{money(row.tax)}</td><td>{money(row.creditTaxable)}</td><td>{money(row.creditTax)}</td><td><strong>{money(row.netTaxable)}</strong></td><td><strong>{money(row.netTax)}</strong></td></tr>)}{!(data.tax?.rates || []).length && <tr><td colSpan="7">No issued tax documents in this period.</td></tr>}</tbody></table></div></section><p className="phase45-finance-note">This is an operational GST summary from Riseora's issued documents, not a substitute for accountant review or GST return filing.</p></>}
      {tab === "payments" && <section className="admin-panel"><div className="admin-panel-head"><div><h2>Payment reconciliation</h2><p>Checks order totals, payment status, provider references, refund totals and delivered COD collections.</p></div><button className="button" disabled={working==="reconcile"} onClick={() => action("reconcile", "/admin/finance/reconcile")}>{working==="reconcile"?"Checking…":"Run reconciliation"}</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Method</th><th>Amount</th><th>Payment</th><th>Reconciliation</th><th></th></tr></thead><tbody>{reviewRows.map((row) => <tr key={row.orderId}><td><Link to={`/admin/orders/${row.orderId}`}><strong>{row.orderNumber}</strong></Link><small>{row.customerName} · {row.orderStatus}</small></td><td>{row.method}</td><td>{money(row.totalAmount)}<small>{row.refundedAmount?`${money(row.refundedAmount)} refunded`:""}</small></td><td><strong>{row.paymentStatus}</strong><small>{row.reference || "No reference"}</small></td><td><span className={`phase45-reconcile ${String(row.reconciliationStatus).toLowerCase()}`}>{row.reconciliationStatus}</span><small>{row.reconciliationNote || "Run reconciliation"}</small></td><td>{row.method==="COD" && row.orderStatus==="DELIVERED" && row.paymentStatus!=="PAID" && <button className="table-action" disabled={working===`cod-${row.orderId}`} onClick={() => collectCod(row)}>Mark collected</button>}</td></tr>)}{!reviewRows.length && <tr><td colSpan="6">No payment exceptions in this period.</td></tr>}</tbody></table></div></section>}
      {tab === "credits" && <section className="admin-panel"><div className="admin-panel-head"><div><h2>Refund credit notes</h2><p>Tax reversals linked to completed returns/refunds.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Credit note</th><th>Invoice</th><th>Return</th><th>Date</th><th>Tax reversal</th><th>Total</th><th></th></tr></thead><tbody>{(data.creditNotes || []).map((row) => <tr key={row.id}><td><strong>{row.creditNoteNumber}</strong></td><td>{row.invoiceNumber}</td><td>{row.returnNumber || `Order ${row.orderNumber}`}</td><td>{new Date(row.issuedAt).toLocaleDateString("en-IN")}</td><td>{money(row.taxTotal)}</td><td><strong>{money(row.grandTotal)}</strong></td><td><Link className="table-action" to={`/admin/credit-notes/${row.id}`}>View</Link></td></tr>)}{!(data.creditNotes || []).length && <tr><td colSpan="7">No credit notes in this period.</td></tr>}</tbody></table></div></section>}
      {tab === "qa" && <div className="phase45-finance-grid"><section className="admin-panel"><div className="admin-panel-head"><div><h2>Catalog tax completeness</h2><p>Active product variants requiring tax-data review.</p></div></div><div className="phase45-gst-kpis"><article><span>Active variants</span><strong>{data.taxQa.activeVariants}</strong></article><article><span>Missing HSN</span><strong>{data.taxQa.missingHsn}</strong></article><article><span>0% GST</span><strong>{data.taxQa.zeroGst}</strong></article></div>{data.taxQa.rows.map((row) => <div className="phase45-finance-line" key={row.id}><span><strong>{row.productName}</strong><small>{row.variantName} · {row.sku}</small></span><b>{pct(row.gstRate)}</b></div>)}</section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Before production filing</h2><p>Finance safeguards built into Riseora.</p></div></div><ul className="phase45-finance-checklist"><li>Confirm GSTIN, PAN and seller state with the accountant.</li><li>Confirm every sellable SKU's HSN/SAC and GST rate.</li><li>Issue invoices before filing sales tax records.</li><li>Issue credit notes for every completed taxable refund.</li><li>Run payment reconciliation and clear all REVIEW REQUIRED rows.</li><li>Export the selected period and reconcile against Razorpay/bank statements.</li></ul></section></div>}
    </>}
  </div>;
}
