import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../../api/http";

export default function AdminAudience() {
  const [messages, setMessages] = useState([]); const [subscribers, setSubscribers] = useState([]);
  const [tab, setTab] = useState("messages"); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  async function load() {
    const [m, n] = await Promise.all([apiFetch(`/admin/contact-messages${status ? `?status=${status}` : ""}`), apiFetch("/admin/newsletter")]);
    setMessages(m.data); setSubscribers(n.data);
  }
  useEffect(() => { load().catch((e) => setError(e.message)); }, [status]);
  const filteredMessages = useMemo(() => !search ? messages : messages.filter((item) => `${item.name} ${item.email} ${item.subject || ""} ${item.message}`.toLowerCase().includes(search.toLowerCase())), [messages, search]);
  const filteredSubscribers = useMemo(() => !search ? subscribers : subscribers.filter((item) => item.email.toLowerCase().includes(search.toLowerCase())), [subscribers, search]);
  async function updateMessage(id, value) { await apiFetch(`/admin/contact-messages/${id}`, { method: "PATCH", body: JSON.stringify({ status: value }) }); await load(); }
  async function toggleSubscriber(item) { await apiFetch(`/admin/newsletter/${item.id}`, { method: "PATCH", body: JSON.stringify({ isActive: !item.isActive }) }); await load(); }
  function exportSubscribers() { const active = subscribers.filter((item) => item.isActive); const csv = ["email,name,source,subscribedAt", ...active.map((item) => [item.email, item.name || "", item.source || "", item.subscribedAt].map((v) => `"${String(v).replaceAll('"','""')}"`).join(","))].join("\n"); const blob = new Blob([csv], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "riseora-newsletter-subscribers.csv"; a.click(); URL.revokeObjectURL(url); }
  return <><div className="admin-page-heading"><div><p className="eyebrow">CUSTOMER CARE</p><h1>Audience & inbox</h1><p>Contact enquiries and newsletter subscribers from the storefront.</p></div></div>{error && <p className="alert error">{error}</p>}<div className="admin-audience-toolbar"><div className="admin-tab-switch"><button className={tab === "messages" ? "active" : ""} onClick={() => setTab("messages")}>Messages ({messages.filter((m) => m.status === "NEW").length} new)</button><button className={tab === "newsletter" ? "active" : ""} onClick={() => setTab("newsletter")}>Newsletter ({subscribers.filter((s) => s.isActive).length})</button></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search…" /></div>{tab === "messages" ? <section className="admin-panel"><div className="admin-panel-head"><div><h2>Contact inbox</h2><p>Update the status as enquiries are handled.</p></div><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>SPAM</option></select></div><div className="contact-message-list">{filteredMessages.map((item) => <article key={item.id} className={item.status === "NEW" ? "contact-message unread" : "contact-message"}><div><strong>{item.name}</strong><a href={`mailto:${item.email}`}>{item.email}</a>{item.phone && <span>{item.phone}</span>}</div><div><b>{item.subject || "General enquiry"}</b><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div><select value={item.status} onChange={(e) => updateMessage(item.id, e.target.value)}><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>SPAM</option></select></article>)}{!filteredMessages.length && <div className="admin-empty">No contact messages found.</div>}</div></section> : <section className="admin-panel"><div className="admin-panel-head"><div><h2>Newsletter audience</h2><p>Consent-based storefront email list.</p></div><button className="button button-secondary" onClick={exportSubscribers}>Export active CSV</button></div><div className="subscriber-list">{filteredSubscribers.map((item) => <div key={item.id}><span><strong>{item.email}</strong><small>{item.source || "storefront"} · {new Date(item.subscribedAt).toLocaleDateString()}</small></span><button className={item.isActive ? "state-toggle active" : "state-toggle"} onClick={() => toggleSubscriber(item)}>{item.isActive ? "Subscribed" : "Unsubscribed"}</button></div>)}{!filteredSubscribers.length && <div className="admin-empty">No subscribers found.</div>}</div></section>}</>;
}
