import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync,spawnSync} from 'node:child_process';import path from 'node:path';import os from 'node:os';
const mount=path.resolve('scripts/phase98-home-mount.mjs');
function fixture(code){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'riseora-phase98-'));fs.mkdirSync(path.join(dir,'pages'),{recursive:true});const file=path.join(dir,'pages','Home.jsx');fs.writeFileSync(file,code);return {dir,file}}
test('phase98 mount injects exactly once and backs up original',()=>{const x=fixture('export default function Home(){return (<main className="home"><h1>Existing home</h1></main>); }');try{execFileSync(process.execPath,[mount,'--path',x.file]);const first=fs.readFileSync(x.file,'utf8');assert.match(first,/<PremiumHomeSections\s*\/>/);assert.match(first,/Existing home/);assert.ok(fs.existsSync(x.file+'.phase98-before-integration.bak'));execFileSync(process.execPath,[mount,'--path',x.file]);assert.equal(first,fs.readFileSync(x.file,'utf8'));}finally{fs.rmSync(x.dir,{recursive:true,force:true})}});
test('phase98 mount refuses unrecognized source without mutation',()=>{const x=fixture('const hello = 5;');try{const result=spawnSync(process.execPath,[mount,'--path',x.file],{encoding:'utf8'});assert.notEqual(result.status,0);assert.equal(fs.readFileSync(x.file,'utf8'),'const hello = 5;');}finally{fs.rmSync(x.dir,{recursive:true,force:true})}});
test('phase98 mount handles JSX fragments',()=>{const x=fixture('export default function Home(){return (<><h1>Original</h1></>)}');try{execFileSync(process.execPath,[mount,'--path',x.file]);assert.match(fs.readFileSync(x.file,'utf8'),/<PremiumHomeSections\s*\/>/)}finally{fs.rmSync(x.dir,{recursive:true,force:true})}});
test('phase98 mount detects missing integration during --check',()=>{const x=fixture('export default function Home(){return (<div/>)}');try{const r=spawnSync(process.execPath,[mount,'--check','--path',x.file]);assert.notEqual(r.status,0)}finally{fs.rmSync(x.dir,{recursive:true,force:true})}});

test('phase98 mount supports named components exported separately',()=>{const x=fixture('function MainLanding(){return (<section><h1>Existing page</h1></section>)}\nexport default MainLanding;');try{execFileSync(process.execPath,[mount,'--path',x.file]);assert.match(fs.readFileSync(x.file,'utf8'),/<PremiumHomeSections\s*\/>/)}finally{fs.rmSync(x.dir,{recursive:true,force:true})}});
