import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';
import {validateTarget,probePublicCandidate} from './phase97-public-contract.mjs';
async function serve(handler,callback){const server=createServer(handler);await new Promise(ok=>server.listen(0,'127.0.0.1',ok));try{return await callback(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(ok=>server.close(ok));}}
function good(req,res){assert.equal(req.method,'GET');if(req.url.startsWith('/api/admin/')){res.writeHead(401);res.end('unauthorized');return;}
 if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<html><head><title>Riseora</title></head><body>Shop</body></html>');return;}
 res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({status:'healthy',version:'97.0'}));}
test('GET-only public probe passes a well formed isolated server',async()=>serve(good,async origin=>{const r=await probePublicCandidate(origin);assert.equal(r.decision,'GO');assert.equal(r.gates.length,6);}));
test('admin endpoint returning 200 blocks launch',async()=>serve((req,res)=>{if(req.url.startsWith('/api/admin/')){res.writeHead(200,{'Content-Type':'application/json'});res.end('{}');}else good(req,res);},async origin=>{const r=await probePublicCandidate(origin);assert(r.gates.some(x=>x.code==='ADMIN_REQUIRES_AUTH'&&x.status==='BLOCK'));}));
test('SPA fallback for readiness cannot produce false PASS',async()=>serve((req,res)=>{if(req.url==='/api/system/health/ready'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<html>SPA</html>');}else good(req,res);},async origin=>{const r=await probePublicCandidate(origin);assert(r.gates.some(x=>x.code==='API_READY'&&x.status==='BLOCK'));}));
test('explicit unhealthy JSON fails despite HTTP 200',async()=>serve((req,res)=>{if(req.url==='/api/system/health/ready'){res.writeHead(200,{'Content-Type':'application/json'});res.end('{"status":"unhealthy"}');}else good(req,res);},async origin=>{const r=await probePublicCandidate(origin);assert(r.gates.some(x=>x.code==='API_READY'&&x.status==='BLOCK'));}));
test('empty JSON cannot certify the release',async()=>serve((req,res)=>{if(req.url==='/api/system/release'){res.writeHead(200,{'Content-Type':'application/json'});res.end('{}');}else good(req,res);},async origin=>{const r=await probePublicCandidate(origin);assert(r.gates.some(x=>x.code==='API_RELEASE'&&x.status==='BLOCK'));}));
test('unsafe public target is rejected',()=>{assert.throws(()=>validateTarget('http://example.com'));assert.throws(()=>validateTarget('https://abc.com/?secret=x'));assert.throws(()=>validateTarget('https://user:pass@abc.com/'));});
test('HTML noindex blocks launch',async()=>serve((req,res)=>{if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<html><meta name="robots" content="noindex"></html>');}else good(req,res);},async origin=>{const r=await probePublicCandidate(origin);assert(r.gates.some(x=>x.code==='STOREFRONT_HOME'&&x.status==='BLOCK'));}));
test('network failure fails closed',async()=>{const r=await probePublicCandidate('http://127.0.0.1:1');assert.equal(r.decision,'NO_GO');});
