import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/http";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const date=v=>v?new Date(v).toLocaleDateString("en-IN"):"—";
export default function AdminMrpCapacityCenter(){
  const [data,setData]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [wc,setWc]=useState({code:"",name:"",warehouseId:"",dailyCapacityMinutes:480,defaultSetupMinutes:15,efficiencyPercent:100});
  const [routing,setRouting]=useState({name:"",outputVariantId:"",operations:[{workCenterId:"",name:"Mix / Process",setupMinutes:15,runMinutesPerUnit:0.2,queueMinutes:0}]});
  const [mrp,setMrp]=useState({warehouseId:"",demandPlanId:"",horizonDays:30,name:"Monthly MRP"}),[mrpPreview,setMrpPreview]=useState(null);
  const [schedule,setSchedule]=useState({warehouseId:"",startDate:new Date().toISOString().slice(0,10),days:14,name:"Two-week production schedule"}),[schedulePreview,setSchedulePreview]=useState(null);
  async function load(){const r=await apiFetch("/admin/ops/phase93-planning/overview");setData(r.data);if(!wc.warehouseId&&r.data.warehouses?.[0])setWc(x=>({...x,warehouseId:r.data.warehouses[0].id}));if(!mrp.warehouseId&&r.data.warehouses?.[0]){setMrp(x=>({...x,warehouseId:r.data.warehouses[0].id}));setSchedule(x=>({...x,warehouseId:r.data.warehouses[0].id}))}}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function run(fn,msg){setBusy(true);setError("");setMessage("");try{await fn();await load();setMessage(msg)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const outputOptions=data?.finishedVariants||[];
  const addOp=()=>setRouting(r=>({...r,operations:[...r.operations,{workCenterId:"",name:"Operation",setupMinutes:10,runMinutesPerUnit:0.1,queueMinutes:0}]}));
  const setOp=(i,k,v)=>setRouting(r=>({...r,operations:r.operations.map((x,n)=>n===i?{...x,[k]:v}:x)}));
  const previewMrp=async()=>{setBusy(true);setError("");try{const r=await apiFetch("/admin/ops/phase93-planning/mrp/preview",{method:"POST",body:{...mrp,horizonDays:Number(mrp.horizonDays)}});setMrpPreview(r.data)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const previewSchedule=async()=>{setBusy(true);setError("");try{const r=await apiFetch("/admin/ops/phase93-planning/schedule/preview",{method:"POST",body:{...schedule,startDate:new Date(`${schedule.startDate}T08:00:00`),days:Number(schedule.days)}});setSchedulePreview(r.data)}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <section className="admin-panel phase93-planning-center">
    <div className="admin-panel-head"><div><p className="eyebrow">PHASE 93 · MRP & CAPACITY CONTROL</p><h2>Material Requirements, Routing & Finite Production Schedule</h2><p>Net Phase 88 demand against stock/open supply, explode active BOMs, convert approved MAKE requirements into production drafts, and schedule routed operations against real work-center capacity.</p></div><button className="button button-secondary" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></div>
    {error&&<p className="alert error">{error}</p>}{message&&<p className="alert success">{message}</p>}
    <div className="phase93-kpis"><article><small>WORK CENTERS</small><strong>{data?.summary?.activeWorkCenters||0}</strong></article><article><small>ACTIVE ROUTINGS</small><strong>{data?.summary?.activeRoutings||0}</strong></article><article><small>OPEN MRP</small><strong>{data?.summary?.openMrp||0}</strong></article><article className={(data?.summary?.buyShortage||0)>0?"danger":""}><small>BUY SHORTAGES</small><strong>{data?.summary?.buyShortage||0}</strong></article><article><small>OPEN PRODUCTION</small><strong>{data?.summary?.openProduction||0}</strong></article><article className={(data?.summary?.unscheduledRouting||0)>0?"danger":""}><small>NO ROUTING</small><strong>{data?.summary?.unscheduledRouting||0}</strong></article></div>
    <div className="phase93-grid-two">
      <div><h3>Work-center master</h3><div className="phase93-form"><input placeholder="Code · MIX-01" value={wc.code} onChange={e=>setWc({...wc,code:e.target.value})}/><input placeholder="Name" value={wc.name} onChange={e=>setWc({...wc,name:e.target.value})}/><select value={wc.warehouseId} onChange={e=>setWc({...wc,warehouseId:e.target.value})}>{(data?.warehouses||[]).map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select><div className="phase93-inline"><label>Capacity min/day<input type="number" value={wc.dailyCapacityMinutes} onChange={e=>setWc({...wc,dailyCapacityMinutes:e.target.value})}/></label><label>Efficiency %<input type="number" value={wc.efficiencyPercent} onChange={e=>setWc({...wc,efficiencyPercent:e.target.value})}/></label></div><button className="button" disabled={busy||!wc.code||!wc.name} onClick={()=>run(()=>apiFetch("/admin/ops/phase93-planning/work-centers",{method:"POST",body:{...wc,dailyCapacityMinutes:Number(wc.dailyCapacityMinutes),defaultSetupMinutes:Number(wc.defaultSetupMinutes),efficiencyPercent:Number(wc.efficiencyPercent)}}),"Work center created.")}>Create work center</button></div><div className="phase93-list">{(data?.workCenters||[]).map(x=><article key={x.id}><b>{x.code} · {x.name}</b><span>{x.dailyCapacityMinutes} min/day · {Number(x.efficiencyPercent)}% efficiency · {x.status}</span></article>)}</div></div>
      <div><h3>Versioned production routing</h3><div className="phase93-form"><input placeholder="Routing name" value={routing.name} onChange={e=>setRouting({...routing,name:e.target.value})}/><select value={routing.outputVariantId} onChange={e=>setRouting({...routing,outputVariantId:e.target.value})}><option value="">Select finished SKU</option>{outputOptions.map(v=><option key={v.id} value={v.id}>{v.sku} · {v.product?.name} · {v.name}</option>)}</select>{routing.operations.map((o,idx)=><div className="phase93-routing-row" key={idx}><select value={o.workCenterId} onChange={e=>setOp(idx,"workCenterId",e.target.value)}><option value="">Work center</option>{(data?.workCenters||[]).filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><input value={o.name} onChange={e=>setOp(idx,"name",e.target.value)}/><input type="number" step="0.01" title="Run minutes/unit" value={o.runMinutesPerUnit} onChange={e=>setOp(idx,"runMinutesPerUnit",e.target.value)}/></div>)}<div className="phase93-actions"><button className="button button-secondary" onClick={addOp}>Add operation</button><button className="button" disabled={busy||!routing.name||!routing.outputVariantId||routing.operations.some(x=>!x.workCenterId)} onClick={()=>run(async()=>{await apiFetch("/admin/ops/phase93-planning/routings",{method:"POST",body:{...routing,operations:routing.operations.map(x=>({...x,setupMinutes:Number(x.setupMinutes),runMinutesPerUnit:Number(x.runMinutesPerUnit),queueMinutes:Number(x.queueMinutes)}))}});setRouting({...routing,name:"",operations:[{workCenterId:"",name:"Mix / Process",setupMinutes:15,runMinutesPerUnit:0.2,queueMinutes:0}]})},"Routing draft created.")}>Create routing</button></div></div><div className="phase93-list">{(data?.routings||[]).slice(0,12).map(x=><article key={x.id}><div><b>{x.name} · v{x.version}</b><span>{x.outputVariant?.sku} · {x.operations?.length||0} operation(s) · {x.status}</span></div>{x.status==="DRAFT"&&<button className="button button-secondary" onClick={()=>run(()=>apiFetch(`/admin/ops/phase93-planning/routings/${x.id}/activate`,{method:"POST"}),"Routing activated.")}>Activate</button>}</article>)}</div></div>
    </div>
    <div className="phase93-grid-two">
      <div><h3>MRP · net demand & BOM explosion</h3><div className="phase93-form"><select value={mrp.demandPlanId} onChange={e=>setMrp({...mrp,demandPlanId:e.target.value})}><option value="">Approved Phase 88 plan</option>{(data?.demandPlans||[]).map(x=><option key={x.id} value={x.id}>{x.name} · {x.recommendedUnits} units</option>)}</select><select value={mrp.warehouseId} onChange={e=>setMrp({...mrp,warehouseId:e.target.value})}>{(data?.warehouses||[]).map(w=><option key={w.id} value={w.id}>{w.code}</option>)}</select><div className="phase93-inline"><label>Horizon days<input type="number" min="7" max="120" value={mrp.horizonDays} onChange={e=>setMrp({...mrp,horizonDays:e.target.value})}/></label><label>Plan name<input value={mrp.name} onChange={e=>setMrp({...mrp,name:e.target.value})}/></label></div><div className="phase93-actions"><button className="button button-secondary" disabled={busy||!mrp.demandPlanId} onClick={previewMrp}>Preview MRP</button><button className="button" disabled={busy||!mrp.demandPlanId} onClick={()=>run(()=>apiFetch("/admin/ops/phase93-planning/mrp",{method:"POST",body:{...mrp,horizonDays:Number(mrp.horizonDays)}}),"MRP draft saved. Review BUY shortages before approval.")}>Save MRP draft</button></div></div>{mrpPreview&&<div className="phase93-preview"><strong>{mrpPreview.summary.makeLines} MAKE · {mrpPreview.summary.buyLines} BUY · {mrpPreview.summary.shortageCount} net shortage line(s)</strong>{mrpPreview.rows.slice(0,14).map(x=><span key={x.variantId}><b>{x.supplyAction}</b> {x.sku} · gross {x.grossRequirementQty} · stock {x.availableStockQty} · scheduled {x.scheduledReceiptQty} · net {x.netRequirementQty} · plan {x.plannedSupplyQty}</span>)}</div>}<div className="phase93-list">{(data?.mrpPlans||[]).slice(0,8).map(p=><article key={p.id}><div><b>{p.planNumber} · {p.name}</b><span>{p.status} · MAKE {p.makeUnits} · BUY {p.buyUnits} · {p.shortageCount} shortage line(s) · MFG {p.productionConvertedAt?"✓":"—"} · PO {p.procurementConvertedAt?"✓":"—"}</span></div><div className="phase93-actions">{p.status==="DRAFT"&&<button className="button button-secondary" onClick={()=>run(()=>apiFetch(`/admin/ops/phase93-planning/mrp/${p.id}/approve`,{method:"POST"}),"MRP plan approved.")}>Approve</button>}{p.status==="APPROVED"&&!p.productionConvertedAt&&<button className="button" onClick={()=>run(()=>apiFetch(`/admin/ops/phase93-planning/mrp/${p.id}/convert-production`,{method:"POST"}),"MAKE requirements converted to production drafts.")}>Create production drafts</button>}{p.status==="APPROVED"&&!p.procurementConvertedAt&&<button className="button button-secondary" onClick={()=>run(()=>apiFetch(`/admin/ops/phase93-planning/mrp/${p.id}/convert-procurement`,{method:"POST"}),"BUY requirements converted to Phase 89 supplier PO drafts.")}>Create supplier PO drafts</button>}</div></article>)}</div></div>
      <div><h3>Finite-capacity production schedule</h3><div className="phase93-form"><select value={schedule.warehouseId} onChange={e=>setSchedule({...schedule,warehouseId:e.target.value})}>{(data?.warehouses||[]).map(w=><option key={w.id} value={w.id}>{w.code}</option>)}</select><div className="phase93-inline"><label>Start<input type="date" value={schedule.startDate} onChange={e=>setSchedule({...schedule,startDate:e.target.value})}/></label><label>Days<input type="number" min="1" max="60" value={schedule.days} onChange={e=>setSchedule({...schedule,days:e.target.value})}/></label></div><input value={schedule.name} onChange={e=>setSchedule({...schedule,name:e.target.value})}/><div className="phase93-actions"><button className="button button-secondary" onClick={previewSchedule}>Preview schedule</button><button className="button" onClick={()=>run(()=>apiFetch("/admin/ops/phase93-planning/schedules",{method:"POST",body:{...schedule,startDate:new Date(`${schedule.startDate}T08:00:00`),days:Number(schedule.days)}}),"Finite-capacity schedule draft created.")}>Save schedule</button></div></div>{schedulePreview&&<div className="phase93-preview"><strong>{schedulePreview.slots.length} operation slot(s) · {schedulePreview.totalMinutes} min · {schedulePreview.lateRiskCount} late risk</strong>{schedulePreview.capacity.map(x=><span key={x.workCenterId}>{x.code} · {x.plannedMinutes}/{x.capacityMinutes} min · {x.loadPercent}% load</span>)}</div>}<div className="phase93-list">{(data?.schedules||[]).slice(0,8).map(s=><article key={s.id}><div><b>{s.scheduleNumber} · {s.name}</b><span>{s.status} · {s.slots?.length||0} slot(s) · late {s.lateRiskCount} · {date(s.horizonStart)}–{date(s.horizonEnd)}</span></div>{s.status==="DRAFT"&&<button className="button" onClick={()=>run(()=>apiFetch(`/admin/ops/phase93-planning/schedules/${s.id}/publish`,{method:"POST"}),"Schedule published; first operation start dates applied to production orders.")}>Publish</button>}</article>)}</div></div>
    </div>
  </section>
}
