import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/http";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const label=v=>String(v||"").replaceAll("_"," ");
const riskClass=v=>`phase88-risk ${String(v||"").toLowerCase()}`;
export default function AdminDemandIntelligenceCenter(){
  const [data,setData]=useState(null),[plans,setPlans]=useState([]),[filter,setFilter]=useState("ACTION"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [form,setForm]=useState({name:"30-day replenishment plan",horizonDays:30,leadTimeDays:14,bufferDays:7});
  const query=`?horizonDays=${form.horizonDays}&leadTimeDays=${form.leadTimeDays}&bufferDays=${form.bufferDays}`;
  async function load(){setError("");const [a,b]=await Promise.all([apiFetch(`/admin/phase88-demand/summary${query}`),apiFetch("/admin/phase88-demand/plans")]);setData(a.data);setPlans(b.data||[])}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function refresh(){setBusy(true);try{await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function createPlan(){setBusy(true);setError("");setMessage("");try{const r=await apiFetch("/admin/phase88-demand/plans",{method:"POST",body:JSON.stringify({...form,horizonDays:Number(form.horizonDays),leadTimeDays:Number(form.leadTimeDays),bufferDays:Number(form.bufferDays)})});setMessage(`Planning snapshot ${r.data.name} created. No stock quantity was changed.`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function approve(id,name){if(!window.confirm(`Approve ${name} as the current replenishment planning record? This does not change stock.`))return;setBusy(true);try{const r=await apiFetch(`/admin/phase88-demand/plans/${id}/approve`,{method:"POST"});setMessage(r.message||"Plan approved.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const rows=useMemo(()=>{const list=data?.rows||[];if(filter==="ALL")return list;if(filter==="ACTION")return list.filter(r=>["OUT_OF_STOCK","CRITICAL","LOW","OVERSTOCK","DORMANT"].includes(r.risk));if(filter==="SUPPLY_RISK")return list.filter(r=>["OUT_OF_STOCK","CRITICAL"].includes(r.risk));return list.filter(r=>r.risk===filter)},[data,filter]);
  const csv=useMemo(()=>["SKU,Product,Variant,Risk,Action,Stock,Safety Stock,Available,Sold 7d,Sold 30d,Daily Velocity,Refill Due,Stock Alerts,Projected Demand,Cover Days,Recommended Reorder,Recommended Purchase Value,Potential Lost Revenue,Overstock Capital",...(data?.rows||[]).map(r=>[r.sku,r.productName,r.variantName,r.risk,r.action,r.currentStock,r.safetyStock,r.availableToSell,r.sold7d,r.sold30d,r.dailyVelocity,r.dueRefillQty,r.pendingStockAlerts,r.projectedDemand,r.coverDays??"",r.recommendedReorderQty,r.recommendedPurchaseValue,r.potentialLostRevenue,r.overstockCapital].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))].join("\n"),[data]);
  function exportCsv(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="riseora-phase88-demand-intelligence.csv";a.click();URL.revokeObjectURL(a.href)}
  const s=data?.summary||{};
  return <section className="phase88-demand-center"><div className="phase88-head"><div><p className="eyebrow">PHASE 88 · DEMAND INTELLIGENCE</p><h2>Inventory Growth & Replenishment Command Center</h2><p>Turn real order velocity, refill demand, safety stock, back-in-stock signals and recent campaign pressure into planning-safe reorder and merchandising decisions. Recommendations never mutate physical stock.</p></div><div className="phase88-head-actions"><button className="button button-secondary" type="button" onClick={exportCsv} disabled={!data?.rows?.length}>Export CSV</button><button className="button button-secondary" type="button" disabled={busy} onClick={refresh}>Refresh forecast</button></div></div>{error&&<p className="alert error">{error}</p>}{message&&<p className="alert success">{message}</p>}
  {data&&<><div className="phase88-kpis"><button onClick={()=>setFilter("ACTION")}><span>ACTION NEEDED</span><strong>{(s.stockoutRisk||0)+(s.criticalRisk||0)+(s.lowRisk||0)+(s.overstock||0)+(s.dormant||0)}</strong><small>Risk + merchandising review</small></button><button className={(s.stockoutRisk||0)+(s.criticalRisk||0)>0?"danger":""} onClick={()=>setFilter("SUPPLY_RISK")}><span>STOCKOUT / CRITICAL</span><strong>{(s.stockoutRisk||0)+(s.criticalRisk||0)}</strong><small>Protect revenue</small></button><article><span>PROJECTED UNITS</span><strong>{s.projectedUnits||0}</strong><small>{form.horizonDays}d planning horizon</small></article><article><span>REORDER UNITS</span><strong>{s.recommendedUnits||0}</strong><small>Lead + buffer protected</small></article><article><span>REORDER CAPITAL</span><strong>{money(s.recommendedPurchaseValue)}</strong><small>Using recorded cost price</small></article><article><span>LOST-REVENUE RISK</span><strong>{money(s.potentialLostRevenue)}</strong><small>Planning estimate</small></article><button onClick={()=>setFilter("OVERSTOCK")}><span>OVERSTOCK CAPITAL</span><strong>{money(s.overstockCapital)}</strong><small>{s.overstock||0} variant(s)</small></button><article><span>REFILL DEMAND</span><strong>{s.dueRefillUnits||0}</strong><small>Due inside horizon</small></article><article><span>BACK-IN-STOCK SIGNALS</span><strong>{s.pendingStockAlerts||0}</strong><small>Pending customer interest</small></article></div>
  <div className="phase88-policy-strip"><span><small>HORIZON</small><b>{data.options.horizonDays}d</b></span><span><small>LEAD TIME</small><b>{data.options.leadTimeDays}d</b></span><span><small>BUFFER</small><b>{data.options.bufferDays}d</b></span><span><small>RECENT CAMPAIGNS</small><b>{data.options.recentCampaignCount}</b></span><span><small>INVENTORY VALUE</small><b>{money(s.inventoryValue)}</b></span></div></>}
  <div className="phase88-layout"><div className="admin-panel phase88-plan-builder"><h3>Create planning snapshot</h3><p className="muted">A snapshot freezes today&apos;s demand evidence for review/approval. Approval is an audit decision only—it does not create supplier orders or change stock.</p><div className="admin-field-grid two"><label>Plan name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Forecast horizon<input type="number" min="7" max="90" value={form.horizonDays} onChange={e=>setForm({...form,horizonDays:e.target.value})}/></label><label>Supplier lead time<input type="number" min="1" max="60" value={form.leadTimeDays} onChange={e=>setForm({...form,leadTimeDays:e.target.value})}/></label><label>Safety buffer days<input type="number" min="0" max="30" value={form.bufferDays} onChange={e=>setForm({...form,bufferDays:e.target.value})}/></label></div><div className="phase88-builder-actions"><button className="button button-secondary" type="button" disabled={busy} onClick={refresh}>Recalculate</button><button className="button" type="button" disabled={busy||!data} onClick={createPlan}>Save replenishment snapshot</button></div></div>
  <div className="admin-panel phase88-plan-history"><h3>Planning history</h3>{!plans.length?<p className="muted">No Phase 88 planning snapshots yet.</p>:plans.slice(0,8).map(p=><article key={p.id}><div><strong>{p.name}</strong><small>{p.horizonDays}d horizon · {p.leadTimeDays}d lead · {p.itemCount} variants</small><small>{p.recommendedUnits} reorder units · {money(p.potentialLostRevenue)} revenue risk</small></div><span className={`phase88-plan-state ${p.status.toLowerCase()}`}>{p.status}</span>{p.status==="DRAFT"&&<button className="button button-secondary" type="button" disabled={busy} onClick={()=>approve(p.id,p.name)}>Approve plan</button>}</article>)}</div></div>
  <div className="phase88-table-panel admin-panel"><div className="phase88-table-head"><div><h3>Variant demand map</h3><p>{rows.length} variant(s) in current view</p></div><div className="phase88-filters">{["ACTION","SUPPLY_RISK","OUT_OF_STOCK","CRITICAL","LOW","HEALTHY","OVERSTOCK","DORMANT","ALL"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{label(f)}</button>)}</div></div><div className="phase88-table-wrap"><table><thead><tr><th>Variant</th><th>Risk</th><th>Stock</th><th>7d / 30d</th><th>Cover</th><th>Forecast</th><th>Reorder</th><th>Signals</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.variantId}><td><strong>{r.productName}</strong><small>{r.variantName} · {r.sku}</small></td><td><span className={riskClass(r.risk)}>{label(r.risk)}</span></td><td><b>{r.currentStock}</b><small>{r.availableToSell} sellable · {r.safetyStock} safety</small></td><td><b>{r.sold7d} / {r.sold30d}</b><small>{Number(r.dailyVelocity).toFixed(2)}/day</small></td><td><b>{r.coverDays==null?"—":`${r.coverDays}d`}</b><small>{r.pendingStockAlerts} alert(s)</small></td><td><b>{r.projectedDemand}</b><small>{r.dueRefillQty} refill due</small></td><td><strong>{r.recommendedReorderQty}</strong><small>{money(r.recommendedPurchaseValue)} planned capital · {money(r.potentialLostRevenue)} revenue risk</small></td><td><small>{r.reason}</small></td><td><span className="phase88-action">{label(r.action)}</span></td></tr>)}</tbody></table></div></div></section>;
}
