import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/http";

const money=(v)=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const dt=(v)=>v?new Date(v).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—";
const fmtMinutes=(v)=>{const m=Number(v||0);if(!m)return "—";if(m<60)return `${Math.round(m)}m`;const h=m/60;if(h<48)return `${h.toFixed(1)}h`;return `${(h/24).toFixed(1)}d`;};

export default function AdminMaintenanceReliabilityCenter(){
  const [data,setData]=useState(null),[days,setDays]=useState(30),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [asset,setAsset]=useState({assetCode:"",name:"",workCenterId:"",manufacturer:"",modelNumber:"",serialNumber:""});
  const [plan,setPlan]=useState({assetId:"",name:"Preventive service",type:"PREVENTIVE",priority:"NORMAL",intervalDays:30,intervalRuntimeMinutes:"",estimatedMinutes:60,instructions:""});
  const [wo,setWo]=useState({assetId:"",type:"CORRECTIVE",priority:"HIGH",title:"",description:""});
  const [drafts,setDrafts]=useState({});
  async function load(){const r=await apiFetch(`/admin/ops/phase95-maintenance/overview?days=${days}`);setData(r.data);const firstCenter=r.data?.workCenters?.[0]?.id||"";const firstAsset=r.data?.assets?.[0]?.id||"";setAsset(a=>a.workCenterId? a:{...a,workCenterId:firstCenter});setPlan(p=>p.assetId? p:{...p,assetId:firstAsset});setWo(w=>w.assetId? w:{...w,assetId:firstAsset});}
  useEffect(()=>{load().catch(e=>setError(e.message));},[days]);
  const run=async(fn,ok)=>{setBusy(true);setError("");setMessage("");try{await fn();setMessage(ok);await load();}catch(e){setError(e.message)}finally{setBusy(false)}};
  const d=(id)=>drafts[id]||{variantId:"",quantity:1,labourMinutes:60,hourlyCost:0,technician:"",rootCause:"",correctiveAction:""};
  const setD=(id,patch)=>setDrafts(x=>({...x,[id]:{...d(id),...patch}}));
  const open=useMemo(()=>data?.workOrders?.filter(x=>["DRAFT","APPROVED","IN_PROGRESS"].includes(x.status))||[],[data]);
  const s=data?.summary||{};
  const createAsset=()=>run(()=>apiFetch("/admin/ops/phase95-maintenance/assets",{method:"POST",body:{...asset,manufacturer:asset.manufacturer||null,modelNumber:asset.modelNumber||null,serialNumber:asset.serialNumber||null}}),"Equipment asset created.");
  const createPlan=()=>run(()=>apiFetch("/admin/ops/phase95-maintenance/plans",{method:"POST",body:{...plan,intervalDays:plan.intervalDays?Number(plan.intervalDays):null,intervalRuntimeMinutes:plan.intervalRuntimeMinutes?Number(plan.intervalRuntimeMinutes):null,estimatedMinutes:Number(plan.estimatedMinutes),instructions:plan.instructions||null}}),"Preventive maintenance plan created.");
  const createWo=()=>run(()=>apiFetch("/admin/ops/phase95-maintenance/work-orders",{method:"POST",body:{...wo,description:wo.description||null}}),"Maintenance work order created.");
  const action=(id,name)=>run(()=>apiFetch(`/admin/ops/phase95-maintenance/work-orders/${id}/${name}`,{method:"POST"}),`Maintenance work order ${name}d.`);
  const issueSpare=(id)=>{const x=d(id);return run(()=>apiFetch(`/admin/ops/phase95-maintenance/work-orders/${id}/spares`,{method:"POST",body:{variantId:x.variantId,quantity:Number(x.quantity)}}),"Spare part issued and inventory reduced.")};
  const complete=(id)=>{const x=d(id);return run(()=>apiFetch(`/admin/ops/phase95-maintenance/work-orders/${id}/complete`,{method:"POST",body:{labourMinutes:Number(x.labourMinutes),hourlyCost:Number(x.hourlyCost),technician:x.technician||null,rootCause:x.rootCause||null,correctiveAction:x.correctiveAction||null}}),"Maintenance completed and asset released.")};

  return <section className="admin-panel phase95-maintenance-center">
    <div className="admin-panel-head"><div><p className="eyebrow">PHASE 95 · MAINTENANCE & RELIABILITY</p><h2>Equipment Reliability, Preventive Maintenance & Spare-Parts Control</h2><p>Prevent repeat breakdowns, control maintenance holds, measure MTBF/MTTR, consume spare parts through inventory, and keep shop-floor operations off unavailable equipment.</p></div><div className="phase95-head-actions"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select><button className="button button-secondary" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></div></div>
    {error&&<p className="alert error">{error}</p>}{message&&<p className="alert success">{message}</p>}
    <div className="phase95-kpis">
      <article><small>ASSETS</small><strong>{s.assets||0}</strong><span>{s.activeAssets||0} active</span></article>
      <article className={(s.unavailableAssets||0)>0?"danger":""}><small>UNAVAILABLE</small><strong>{s.unavailableAssets||0}</strong><span>Maintenance / breakdown / hold</span></article>
      <article className={(s.overduePlans||0)>0?"danger":""}><small>PM DUE</small><strong>{s.overduePlans||0}</strong><span>Calendar/runtime maintenance</span></article>
      <article><small>OPEN WORK ORDERS</small><strong>{s.openWorkOrders||0}</strong><span>{s.breakdownWorkOrders||0} corrective</span></article>
      <article><small>MAINTENANCE COST</small><strong>{money(s.maintenanceCost)}</strong><span>{days}-day completed cost</span></article>
      <article className={(s.lowSpareParts||0)>0?"danger":""}><small>LOW SPARES</small><strong>{s.lowSpareParts||0}</strong><span>At/below low-stock threshold</span></article>
    </div>

    <div className="phase95-grid-three">
      <div className="phase95-card"><h3>Equipment master</h3><div className="phase95-form"><div className="phase95-inline"><input placeholder="Asset code" value={asset.assetCode} onChange={e=>setAsset({...asset,assetCode:e.target.value})}/><input placeholder="Asset name" value={asset.name} onChange={e=>setAsset({...asset,name:e.target.value})}/></div><select value={asset.workCenterId} onChange={e=>setAsset({...asset,workCenterId:e.target.value})}><option value="">Work center</option>{(data?.workCenters||[]).map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><div className="phase95-inline"><input placeholder="Manufacturer" value={asset.manufacturer} onChange={e=>setAsset({...asset,manufacturer:e.target.value})}/><input placeholder="Model" value={asset.modelNumber} onChange={e=>setAsset({...asset,modelNumber:e.target.value})}/></div><input placeholder="Serial number" value={asset.serialNumber} onChange={e=>setAsset({...asset,serialNumber:e.target.value})}/><button className="button" disabled={busy||!asset.workCenterId||asset.assetCode.trim().length<2||asset.name.trim().length<2} onClick={createAsset}>Add equipment asset</button></div></div>
      <div className="phase95-card"><h3>Preventive maintenance plan</h3><div className="phase95-form"><select value={plan.assetId} onChange={e=>setPlan({...plan,assetId:e.target.value})}><option value="">Asset</option>{(data?.assets||[]).filter(x=>x.status!=="RETIRED").map(x=><option key={x.id} value={x.id}>{x.assetCode} · {x.name}</option>)}</select><input placeholder="Plan name" value={plan.name} onChange={e=>setPlan({...plan,name:e.target.value})}/><div className="phase95-inline"><select value={plan.type} onChange={e=>setPlan({...plan,type:e.target.value})}><option>PREVENTIVE</option><option>INSPECTION</option><option>CALIBRATION</option></select><select value={plan.priority} onChange={e=>setPlan({...plan,priority:e.target.value})}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><div className="phase95-inline"><label>Every days<input type="number" min="1" value={plan.intervalDays} onChange={e=>setPlan({...plan,intervalDays:e.target.value})}/></label><label>Every runtime min<input type="number" min="1" value={plan.intervalRuntimeMinutes} onChange={e=>setPlan({...plan,intervalRuntimeMinutes:e.target.value})}/></label></div><textarea placeholder="Instructions" value={plan.instructions} onChange={e=>setPlan({...plan,instructions:e.target.value})}/><button className="button" disabled={busy||!plan.assetId||!plan.name.trim()} onClick={createPlan}>Create maintenance plan</button><button className="button button-secondary" disabled={busy} onClick={()=>run(()=>apiFetch('/admin/ops/phase95-maintenance/work-orders/generate-due',{method:'POST'}),'Due preventive work orders generated.')}>Generate due PM work</button></div></div>
      <div className="phase95-card"><h3>Manual maintenance work order</h3><div className="phase95-form"><select value={wo.assetId} onChange={e=>setWo({...wo,assetId:e.target.value})}><option value="">Asset</option>{(data?.assets||[]).filter(x=>x.status!=="RETIRED").map(x=><option key={x.id} value={x.id}>{x.assetCode} · {x.name}</option>)}</select><div className="phase95-inline"><select value={wo.type} onChange={e=>setWo({...wo,type:e.target.value})}><option>CORRECTIVE</option><option>PREVENTIVE</option><option>INSPECTION</option><option>CALIBRATION</option></select><select value={wo.priority} onChange={e=>setWo({...wo,priority:e.target.value})}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><input placeholder="Work title" value={wo.title} onChange={e=>setWo({...wo,title:e.target.value})}/><textarea placeholder="Problem / scope" value={wo.description} onChange={e=>setWo({...wo,description:e.target.value})}/><button className="button" disabled={busy||!wo.assetId||wo.title.trim().length<2} onClick={createWo}>Create work order</button></div></div>
    </div>

    <div className="phase95-grid-two">
      <div className="phase95-card"><div className="phase95-section-head"><div><h3>Reliability by equipment</h3><p>MTBF and MTTR are derived from traced breakdown downtime and runtime evidence.</p></div><span>{data?.reliability?.length||0} assets</span></div><div className="phase95-table-wrap"><table><thead><tr><th>Asset</th><th>Work center</th><th>Breakdowns</th><th>MTBF</th><th>MTTR</th><th>Availability</th></tr></thead><tbody>{(data?.reliability||[]).map(x=><tr key={x.assetId}><td><b>{x.assetCode}</b><small>{x.name}</small></td><td>{x.workCenter?.code}</td><td>{x.breakdownCount}</td><td>{fmtMinutes(x.mtbfMinutes)}</td><td>{fmtMinutes(x.mttrMinutes)}</td><td>{Number(x.availabilityPercent||0).toFixed(1)}%</td></tr>)}</tbody></table></div></div>
      <div className="phase95-card"><h3>Preventive plan due list</h3><div className="phase95-list">{(data?.plans||[]).map(x=>{const due=(data?.duePlans||[]).some(d=>d.id===x.id);return <article key={x.id} className={due?"danger":""}><div><b>{x.asset?.assetCode} · {x.name}</b><span>{x.type} · {x.priority}</span><small>Date due {dt(x.nextDueAt)} · runtime due {x.nextDueRuntimeMinutes??"—"} min · current {x.asset?.cumulativeRuntimeMinutes||0}</small></div><span className={`phase95-chip ${due?'danger':'ok'}`}>{due?'DUE':'PLANNED'}</span></article>})}</div></div>
    </div>

    <div className="phase95-card"><div className="phase95-section-head"><div><h3>Maintenance work-order board</h3><p>Breakdown downtime creates corrective work automatically when an assigned equipment asset exists. Spare issue reduces actual warehouse inventory and becomes work-order cost evidence.</p></div><span>{open.length} open</span></div><div className="phase95-workorders">{open.map(x=>{const q=d(x.id);return <article key={x.id} className={x.priority==='CRITICAL'?"danger":""}><div className="phase95-wo-head"><div><b>{x.workOrderNumber} · {x.title}</b><span>{x.asset?.assetCode} · {x.asset?.workCenter?.code} · {x.type} · {x.priority}</span><small>{x.status} · due {dt(x.dueAt)} · spares {money(x.spareCost)} · total {money(x.totalCost)}</small></div><span className={`phase95-chip ${x.status.toLowerCase()}`}>{x.status}</span></div><div className="phase95-actions">{x.status==='DRAFT'&&<button className="button button-secondary" disabled={busy} onClick={()=>action(x.id,'approve')}>Approve</button>}{x.status==='APPROVED'&&<button className="button" disabled={busy} onClick={()=>action(x.id,'start')}>Start maintenance</button>}{x.status==='IN_PROGRESS'&&<><select value={q.variantId} onChange={e=>setD(x.id,{variantId:e.target.value})}><option value="">Spare part</option>{(data?.spareParts||[]).map(v=><option key={v.id} value={v.id}>{v.sku} · avail {v.availableToSell}</option>)}</select><input type="number" min="1" value={q.quantity} onChange={e=>setD(x.id,{quantity:e.target.value})}/><button className="button button-secondary" disabled={busy||!q.variantId} onClick={()=>issueSpare(x.id)}>Issue spare</button></>}</div>{x.status==='IN_PROGRESS'&&<div className="phase95-complete-grid"><label>Labour min<input type="number" min="0" value={q.labourMinutes} onChange={e=>setD(x.id,{labourMinutes:e.target.value})}/></label><label>Hourly cost<input type="number" min="0" value={q.hourlyCost} onChange={e=>setD(x.id,{hourlyCost:e.target.value})}/></label><input placeholder="Technician" value={q.technician} onChange={e=>setD(x.id,{technician:e.target.value})}/><input placeholder="Root cause" value={q.rootCause} onChange={e=>setD(x.id,{rootCause:e.target.value})}/><input placeholder="Corrective action" value={q.correctiveAction} onChange={e=>setD(x.id,{correctiveAction:e.target.value})}/><button className="button" disabled={busy} onClick={()=>complete(x.id)}>Complete & release asset</button></div>}</article>})}</div></div>

    <div className="phase95-card"><div className="phase95-section-head"><div><h3>Spare-parts health</h3><p>Classify maintenance inventory as SPARE_PART in Phase 92 inventory roles. Phase 89 procurement can source these hidden active SKUs; Phase 88 retail demand continues to ignore them.</p></div></div><div className="phase95-table-wrap"><table><thead><tr><th>SKU</th><th>Part</th><th>On hand</th><th>Safety</th><th>Available</th><th>Low at</th><th>Status</th></tr></thead><tbody>{(data?.spareParts||[]).map(x=><tr key={x.id}><td>{x.sku}</td><td>{x.product?.name} · {x.name}</td><td>{x.stockQuantity}</td><td>{x.safetyStock}</td><td>{x.availableToSell}</td><td>{x.lowStockThreshold}</td><td><span className={`phase95-chip ${x.availableToSell<=x.lowStockThreshold?'danger':'ok'}`}>{x.availableToSell<=x.lowStockThreshold?'REORDER':'HEALTHY'}</span></td></tr>)}</tbody></table></div></div>
  </section>;
}
