import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../api/http';
import PremiumHomeSections from './PremiumHomeSections';

const TEMPLATES=[
 ['hero','Signature hero','A cinematic image, statement headline and two editorial actions.'],
 ['split','Editorial story','An image + text feature with generous spacing.'],
 ['collections','Collections grid','A campaign, launch, routine or category card gallery.'],
 ['features','Brand promises','Three or more intentional brand benefits.'],
 ['story','Our philosophy','Full-bleed brand narrative and storytelling.'],
 ['productShelf','Curated picks','Linkable product cards with your own imagery.'],
 ['testimonials','Social proof','Editable customer quotes (publish only verified claims).'],
 ['faq','Questions & answers','Accessible expandable FAQ content.'],
 ['marquee','Moving wordmark','Animated typography separator.'],
 ['gallery','Editorial gallery','A visual image + caption gallery.'],
 ['newsletter','Community invitation','Link to account creation; no automatic opt-in.'],
 ['countdown','Launch countdown','A timed campaign message (no artificial sale).'],
];
const EMPTY_ITEM=()=>({id:'item_'+crypto.randomUUID().slice(0,12),title:'',body:'',image:'',label:'',href:'',badge:''});
const makeSection=type=>({id:'section_'+crypto.randomUUID().slice(0,12),type,enabled:true,eyebrow:'A LITTLE SOMETHING SPECIAL',heading:type==='hero'?'Made for your everyday glow':TEMPLATES.find(([t])=>t===type)?.[1]||'New section',subheading:'Write your own story here.',image:'',imageAlt:'',mobileImage:'',ctaText:'Explore now',ctaHref:'/shop',secondaryCtaText:'',secondaryCtaHref:'',align:'left',style:type==='hero'?'accent':'light',height:type==='hero'?'tall':'regular',animation:'rise',items:[],endAt:type==='countdown'?new Date(Date.now()+7*86400000).toISOString():null,productIds:[]});
const Field=({label,value,onChange,placeholder='',type='text',rows=0})=><label className="phase98-field"><span>{label}</span>{rows?<textarea rows={rows} value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>;
const Choose=({label,value,onChange,options})=><label className="phase98-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;
const selectOf=(values)=>values.map(x=>[x,x.replace(/_/g,' ')]);
export default function AdminVisualStudio(){
 const [open,setOpen]=useState(false),[settings,setSettings]=useState(null),[library,setLibrary]=useState([]),[state,setState]=useState(null),[doc,setDoc]=useState(null),[active,setActive]=useState(null),[error,setError]=useState(''),[info,setInfo]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('desktop'),[history,setHistory]=useState([]),[filter,setFilter]=useState('builder');
 const reload=useCallback(async()=>{const [one,two]=await Promise.all([apiFetch('/admin/ops/phase98-studio'),apiFetch('/admin/ops/phase98-studio/history')]);setState(one.data);setDoc(one.data.draft);setActive(prev=>one.data.draft.sections.some(s=>s.id===prev)?prev:one.data.draft.sections[0]?.id);setHistory(two.data||[]);},[]);
 useEffect(()=>{reload().catch(e=>setError(e.message));apiFetch('/admin/banners').then(r=>setLibrary((r.data||[]).filter(b=>b.imageUrl))).catch(()=>{});apiFetch('/admin/ops/settings').then(r=>setSettings(r.data)).catch(()=>{});},[reload]);
 const sections=doc?.sections||[],selected=useMemo(()=>sections.find(s=>s.id===active),[sections,active]);
 const editDocument=(patch)=>setDoc(prev=>({...prev,...patch}));
 const setSection=(id,patch)=>setDoc(prev=>({...prev,sections:prev.sections.map(s=>s.id===id?{...s,...patch}:s)}));
 const move=(id,direction)=>setDoc(prev=>{const items=[...prev.sections],at=items.findIndex(x=>x.id===id),target=at+direction;if(target<0||target>=items.length)return prev;[items[at],items[target]]=[items[target],items[at]];return {...prev,sections:items}});
 const exportDraft=()=>{const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`riseora-design-draft-r${state.revision}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 async function saveSettings(){if(!settings)return;setBusy(true);setError('');try{const fields=['brandTagline','logoUrl','logoMarkUrl','logoAlt','announcementText','announcementSecondary','seoTitle','seoDescription','instagramUrl','facebookUrl','youtubeUrl'];const body={};for(const key of fields)if(typeof settings[key]==='string')body[key]=settings[key];const result=await apiFetch('/admin/ops/settings',{method:'PATCH',body});if(!result.success)throw new Error(result.message||'Could not save');setInfo('Sitewide brand settings saved.');}catch(e){setError(e.message)}finally{setBusy(false)}}
 const addSection=(type)=>{const next=makeSection(type);setDoc(prev=>({...prev,sections:[...prev.sections,next]}));setActive(next.id);setFilter('builder');};
 const cloneSection=id=>{const s=sections.find(x=>x.id===id);if(!s)return;const copy={...s,id:'section_'+crypto.randomUUID().slice(0,12),heading:s.heading+' (copy)',items:s.items.map(x=>({...x,id:'item_'+crypto.randomUUID().slice(0,12)}))};setDoc(prev=>({...prev,sections:[...prev.sections,copy]}));setActive(copy.id)};
 async function action(kind,extra){setBusy(true);setError('');setInfo('');try{
  let response;
  if(kind==='save')response=await apiFetch('/admin/ops/phase98-studio/draft',{method:'PUT',body:JSON.stringify({expectedRevision:state.revision,document:doc})});
  if(kind==='publish'){if(!window.confirm('Publish the CURRENT SAVED draft to customers? Unsaved edits will not be published.'))return;response=await apiFetch('/admin/ops/phase98-studio/publish',{method:'POST',body:JSON.stringify({expectedRevision:state.revision})});}
  if(kind==='restore'){if(!window.confirm(`Restore published revision ${extra} as an editable DRAFT? The live website will not change until you publish.`))return;response=await apiFetch(`/admin/ops/phase98-studio/restore/${extra}`,{method:'POST',body:JSON.stringify({expectedRevision:state.revision})});}
  if(!response?.success)throw new Error(response?.message||'Operation failed');
  await reload();setInfo(kind==='save'?'Draft saved. Public website remains unchanged.':kind==='publish'?'Published successfully. Public caches may take up to 30 seconds to refresh.':'Archived publication restored to draft. Live site unchanged.');
 }catch(e){setError(e.message||'Request failed');}finally{setBusy(false)}}
 if(!open)return <section className="admin-panel phase98-studio-launcher"><div><p className="eyebrow">PHASE 98 · PREMIUM VISUAL STUDIO</p><h2>Shape the Riseora experience</h2><p>Build banners, editorial pages, galleries and motion-rich sections without disturbing the live storefront until you publish.</p></div><button type="button" className="button" onClick={()=>setOpen(true)}>Open Visual Studio ↗</button></section>;
 if(!doc)return <section className="admin-panel phase98-admin-studio"><h2>Visual Studio</h2>{error?<p role="alert" className="alert error">{error}</p>:<p>Loading design studio…</p>}</section>;
 return <section className="admin-panel phase98-admin-studio" id="phase98-visual-studio">
  <div className="phase98-admin-heading"><div><p className="eyebrow">PHASE 98 · PREMIUM EXPERIENCE STUDIO</p><h2>Your storefront. Your vision.</h2><p>Design cinematic pages, create new banners and collections, adjust motion and identity, then publish when you are ready.</p></div><div className="phase98-admin-actions"><button type="button" className="button button-secondary" onClick={()=>setOpen(false)}>Close studio</button><button type="button" className="button button-secondary" onClick={exportDraft}>Export design JSON</button><button type="button" className="button button-secondary" onClick={()=>reload().catch(e=>setError(e.message))} disabled={busy}>Reload</button><button type="button" className="button button-secondary" disabled={busy} onClick={()=>action('save')}>Save draft</button><button type="button" className="button" disabled={busy||state.publishedRevision===state.revision} onClick={()=>action('publish')}>Publish saved design ↗</button></div></div>
  <div className="phase98-admin-meta"><span>Working revision <strong>{state.revision}</strong></span><span>Live revision <strong>{state.publishedRevision||'None yet'}</strong></span><span>{state.publishedAt?`Live since ${new Date(state.publishedAt).toLocaleString()}`:'Original homepage remains live'}</span></div>
  {info&&<p className="alert success" role="status">{info}</p>}{error&&<p className="alert error" role="alert">{error}</p>}
  <div className="phase98-admin-tabs" role="tablist">{[['builder','Page builder'],['identity','Brand & motion'],['templates','New sections'],['history','Publish history']].map(([v,t])=><button type="button" role="tab" aria-selected={filter===v} className={filter===v?'selected':''} onClick={()=>setFilter(v)} key={v}>{t}</button>)}</div>
  {filter==='identity'&&<div className="phase98-identity-grid"><div className="phase98-editor-card"><h3>Visual identity</h3><Choose label="Brand palette" value={doc.brand.accent} onChange={v=>editDocument({brand:{...doc.brand,accent:v}})} options={selectOf(['sage','gold','terracotta','rose','midnight'])}/><Choose label="Typography" value={doc.brand.typography} onChange={v=>editDocument({brand:{...doc.brand,typography:v}})} options={selectOf(['editorial','modern','classic'])}/><Choose label="Corners" value={doc.brand.radius} onChange={v=>editDocument({brand:{...doc.brand,radius:v}})} options={selectOf(['soft','rounded','sharp'])}/><Choose label="Motion intensity" value={doc.brand.motion} onChange={v=>editDocument({brand:{...doc.brand,motion:v}})} options={selectOf(['subtle','immersive','off'])}/><Choose label="Spacing" value={doc.brand.density} onChange={v=>editDocument({brand:{...doc.brand,density:v}})} options={selectOf(['airy','balanced','compact'])}/></div><div className="phase98-editor-card"><h3>Announcement & SEO</h3><label className="phase98-switch"><input type="checkbox" checked={doc.announcement.enabled} onChange={e=>editDocument({announcement:{...doc.announcement,enabled:e.target.checked}})}/> Enable announcement ribbon</label><Field label="Announcement copy" value={doc.announcement.text} onChange={v=>editDocument({announcement:{...doc.announcement,text:v}})}/><Field label="Announcement link" value={doc.announcement.href} onChange={v=>editDocument({announcement:{...doc.announcement,href:v}})}/><Field label="SEO title" value={doc.seo.title} onChange={v=>editDocument({seo:{...doc.seo,title:v}})}/><Field label="SEO description" rows={3} value={doc.seo.description} onChange={v=>editDocument({seo:{...doc.seo,description:v}})}/><p className="phase98-admin-hint">SEO metadata is updated on the published homepage. Existing global SEO infrastructure remains unchanged.</p></div>
 {settings&&<div className="phase98-editor-card phase98-sitewide-card"><div className="phase98-items-head"><h3>Sitewide brand & contact identity</h3><button type="button" className="button button-secondary" disabled={busy} onClick={saveSettings}>Save sitewide settings</button></div><p>These existing Riseora settings control the original site header, contact information and global SEO independently from the draft homepage.</p><div className="phase98-fields-two">{[['brandTagline','Brand tagline'],['logoUrl','Logo URL'],['logoMarkUrl','Logo mark URL'],['logoAlt','Logo alt text'],['announcementText','Site announcement'],['announcementSecondary','Secondary ribbon'],['seoTitle','Global SEO title'],['seoDescription','Global SEO description'],['instagramUrl','Instagram URL'],['facebookUrl','Facebook URL'],['youtubeUrl','YouTube URL']].map(([key,label])=><Field key={key} label={label} value={settings[key]||''} onChange={v=>setSettings(current=>({...current,[key]:v}))}/>)}</div><small className="phase98-admin-hint">Only supported sitewide fields are sent to the existing settings API; payment, fulfilment and legal policies remain under their dedicated admin controls.</small></div>}</div>}
  {filter==='templates'&&<div className="phase98-template-grid">{TEMPLATES.map(([id,label,desc],i)=><button type="button" className="phase98-template" key={id} disabled={sections.length>=35} onClick={()=>addSection(id)}><span>{String(i+1).padStart(2,'0')}</span><strong>{label}</strong><small>{desc}</small><em>+ Add section</em></button>)}</div>}
  {filter==='history'&&<div className="phase98-editor-card"><h3>Published versions</h3><p>Restoring a historical version only creates a new draft. It cannot automatically change the public website.</p>{history.map(h=><div className="phase98-history-row" key={h.id}><span><strong>Revision {h.revision}</strong><small>{new Date(h.publishedAt).toLocaleString()}</small></span><button type="button" disabled={busy} className="button button-secondary" onClick={()=>action('restore',h.revision)}>Restore as draft</button></div>)}{!history.length&&<p>No published versions yet.</p>}</div>}
  {filter==='builder'&&<div className="phase98-builder-layout"><aside className="phase98-section-list"><div className="phase98-list-title"><strong>Page sections</strong><small>{sections.length} / 35</small></div>{sections.map((s,index)=><div key={s.id} className={`phase98-section-row ${active===s.id?'selected':''}`}><button type="button" className="phase98-section-select" onClick={()=>setActive(s.id)}><span>{String(index+1).padStart(2,'0')} · {s.type}</span><strong>{s.heading||'Untitled section'}</strong></button><div className="phase98-section-row-actions"><button type="button" title="Move up" aria-label={`Move ${s.heading} up`} onClick={()=>move(s.id,-1)} disabled={!index}>↑</button><button type="button" title="Move down" aria-label={`Move ${s.heading} down`} onClick={()=>move(s.id,1)} disabled={index===sections.length-1}>↓</button><button type="button" title="Duplicate" aria-label={`Duplicate ${s.heading}`} disabled={sections.length>=35} onClick={()=>cloneSection(s.id)}>⧉</button></div></div>)}<button className="phase98-add-link" type="button" onClick={()=>setFilter('templates')}>+ Add a section</button></aside>
  <div className="phase98-editor-card phase98-detail-editor">{selected?<><div className="phase98-detail-title"><div><small>EDIT SECTION · {selected.type.toUpperCase()}</small><h3>{selected.heading||'New section'}</h3></div><button className="button button-secondary" type="button" disabled={sections.length<=1} onClick={()=>{if(window.confirm('Remove this section from draft?')){setDoc(prev=>({...prev,sections:prev.sections.filter(x=>x.id!==selected.id)}));setActive(sections.find(x=>x.id!==selected.id)?.id)}}}>Remove</button></div><label className="phase98-switch"><input type="checkbox" checked={selected.enabled} onChange={e=>setSection(selected.id,{enabled:e.target.checked})}/> Visible in published homepage</label>
  <div className="phase98-fields-two"><Field label="Eyebrow" value={selected.eyebrow} onChange={v=>setSection(selected.id,{eyebrow:v})}/><Field label="Headline" value={selected.heading} onChange={v=>setSection(selected.id,{heading:v})}/></div><Field label="Description" rows={3} value={selected.subheading} onChange={v=>setSection(selected.id,{subheading:v})}/><div className="phase98-fields-two"><Field label="Desktop image URL" value={selected.image} placeholder="/uploads/your-banner.webp" onChange={v=>setSection(selected.id,{image:v})}/><Field label="Mobile image URL" value={selected.mobileImage} placeholder="/uploads/mobile.webp" onChange={v=>setSection(selected.id,{mobileImage:v})}/></div>{library.length>0&&<div className="phase98-library-strip"><div><strong>Existing media library</strong><small>Choose an uploaded banner image or paste a secure URL above.</small></div><div className="phase98-library-items">{library.slice(0,16).map(b=><button type="button" key={b.id} title={`Use ${b.title}`} onClick={()=>setSection(selected.id,{image:b.imageUrl||'',mobileImage:b.mobileImageUrl||'',imageAlt:b.imageAlt||b.title||''})}><img src={b.imageUrl} alt={b.imageAlt||b.title} loading="lazy"/><span>Use image ↗</span></button>)}</div></div>}
  <Field label="Image alternative text" value={selected.imageAlt} onChange={v=>setSection(selected.id,{imageAlt:v})}/><div className="phase98-fields-two"><Field label="Primary CTA label" value={selected.ctaText} onChange={v=>setSection(selected.id,{ctaText:v})}/><Field label="Primary CTA path" value={selected.ctaHref} onChange={v=>setSection(selected.id,{ctaHref:v})}/><Field label="Secondary CTA label" value={selected.secondaryCtaText} onChange={v=>setSection(selected.id,{secondaryCtaText:v})}/><Field label="Secondary CTA path" value={selected.secondaryCtaHref} onChange={v=>setSection(selected.id,{secondaryCtaHref:v})}/></div><div className="phase98-fields-two"><Choose label="Colour treatment" value={selected.style} onChange={v=>setSection(selected.id,{style:v})} options={selectOf(['light','dark','accent','image'])}/><Choose label="Motion" value={selected.animation} onChange={v=>setSection(selected.id,{animation:v})} options={selectOf(['none','fade','rise','zoom','slide'])}/><Choose label="Height" value={selected.height} onChange={v=>setSection(selected.id,{height:v})} options={selectOf(['compact','regular','tall'])}/><Choose label="Alignment" value={selected.align} onChange={v=>setSection(selected.id,{align:v})} options={selectOf(['left','center','right'])}/></div>
  {selected.type==='countdown'&&<Field label="Campaign end (ISO 8601 with timezone)" value={selected.endAt||''} placeholder="2026-12-31T23:59:00+05:30" onChange={v=>setSection(selected.id,{endAt:v||null})}/>}
  <div className="phase98-items-editor"><div className="phase98-items-head"><h4>Cards, banners & content blocks</h4><button className="button button-secondary" type="button" disabled={selected.items.length>=18} onClick={()=>setSection(selected.id,{items:[...selected.items,EMPTY_ITEM()]})}>+ Add card</button></div>{selected.items.map((item,i)=><article key={item.id} className="phase98-item-editor"><div className="phase98-item-top"><strong>Item {i+1}</strong><button type="button" onClick={()=>setSection(selected.id,{items:selected.items.filter(x=>x.id!==item.id)})}>Remove</button></div><div className="phase98-fields-two">{[['title','Headline'],['label','Small label'],['badge','Badge'],['image','Image URL'],['href','Link']].map(([key,label])=><Field key={key} label={label} value={item[key]} onChange={v=>setSection(selected.id,{items:selected.items.map(x=>x.id===item.id?{...x,[key]:v}:x)})}/>)}</div><Field rows={2} label="Description / quote" value={item.body} onChange={v=>setSection(selected.id,{items:selected.items.map(x=>x.id===item.id?{...x,body:v}:x)})}/></article>)}</div>
  </>:<p>Choose a section or add a template.</p>}</div></div>}
  <div className="phase98-preview-heading"><div><p className="eyebrow">DRAFT · INSTANT PREVIEW</p><h3>See the vision before customers do.</h3><p>Your unsaved changes appear below. They are not public.</p></div><div className="phase98-device-toggle"><button type="button" className={view==='desktop'?'selected':''} onClick={()=>setView('desktop')}>Desktop</button><button type="button" className={view==='mobile'?'selected':''} onClick={()=>setView('mobile')}>Mobile</button></div></div><div className={`phase98-preview-window phase98-preview-${view}`}><PremiumHomeSections preview previewDocument={doc}/></div>
 </section>;
}
