import { useEffect, useState } from "react";
import { apiFetch } from "../api/http";
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const label = (value) => String(value || "").replaceAll("_", " ");
export default function AdminRetentionGrowthCenter() {
  const [summary, setSummary] = useState(null); const [campaigns, setCampaigns] = useState([]); const [preview, setPreview] = useState(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: "", segment: "AT_RISK", benefitKind: "COUPON", couponAmount: 200, rewardPoints: 200, validDays: 30, audiencePolicy: "ACCOUNT_PERSONALIZATION" });
  const payload = () => form.benefitKind === "COUPON" ? { name: form.name || `${label(form.segment)} lifecycle campaign`, segment: form.segment, benefitKind: "COUPON", couponAmount: Number(form.couponAmount), validDays: Number(form.validDays), audiencePolicy: form.audiencePolicy } : { name: form.name || `${label(form.segment)} lifecycle campaign`, segment: form.segment, benefitKind: "REWARD_POINTS", rewardPoints: Number(form.rewardPoints), validDays: Number(form.validDays), audiencePolicy: form.audiencePolicy };
  async function load() { const [a,b] = await Promise.all([apiFetch("/admin/phase86-retention/summary"), apiFetch("/admin/phase86-retention/campaigns")]); setSummary(a.data); setCampaigns(b.data || []); }
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  async function runPreview() { setBusy(true); setError(""); try { const r = await apiFetch("/admin/phase86-retention/preview", { method: "POST", body: JSON.stringify(payload()) }); setPreview(r.data); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function createDraft() { setBusy(true); setError(""); setMessage(""); try { const r = await apiFetch("/admin/phase86-retention/campaigns", { method: "POST", body: JSON.stringify(payload()) }); setMessage(`Draft ${r.data.name} created.`); setPreview(null); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function activate(id, name) { if (!window.confirm(`Activate ${name}? Eligible customers will receive the benefit immediately.`)) return; setBusy(true); setError(""); try { const r = await apiFetch(`/admin/phase86-retention/campaigns/${id}/activate`, { method: "POST" }); setMessage(`Campaign activated · ${r.data.issued} issued · ${r.data.suppressed} suppressed.`); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <section className="phase86-growth-center">
    <div className="phase86-growth-head"><div><p className="eyebrow">PHASE 86 · RETENTION INTELLIGENCE</p><h2>Lifecycle Growth Control Center</h2><p>Find at-risk, lapsed, loyal and VIP cohorts; preview suppression reasons; then issue controlled personal benefits without marketing into unresolved service problems.</p></div></div>
    {error && <p className="alert error">{error}</p>}{message && <p className="alert success">{message}</p>}
    {summary && <><div className="phase86-growth-kpis"><article><span>CUSTOMERS</span><strong>{summary.totalCustomers}</strong></article><article><span>AT RISK</span><strong>{summary.segments?.AT_RISK || 0}</strong></article><article><span>LAPSED</span><strong>{summary.segments?.LAPSED || 0}</strong></article><article><span>VIP</span><strong>{summary.segments?.VIP || 0}</strong></article><article><span>REFILL DUE</span><strong>{summary.refillDue || 0}</strong></article><article><span>ISSUED · 30D</span><strong>{summary.issued30d || 0}</strong></article></div><div className="phase86-segment-strip">{["NEW","ACTIVE","LOYAL","VIP","AT_RISK","LAPSED"].map((s) => <span key={s}><small>{label(s)}</small><strong>{summary.segments?.[s] || 0}</strong></span>)}</div></>}
    <div className="phase86-growth-grid"><div className="admin-panel phase86-campaign-builder"><h3>Build lifecycle campaign</h3><div className="admin-field-grid two"><label>Name<input value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="At-risk customer care" /></label><label>Segment<select value={form.segment} onChange={(e) => setForm({...form,segment:e.target.value})}>{["NEW","ACTIVE","LOYAL","VIP","AT_RISK","LAPSED"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Benefit<select value={form.benefitKind} onChange={(e) => setForm({...form,benefitKind:e.target.value})}><option value="COUPON">Personal coupon</option><option value="REWARD_POINTS">Reward points</option></select></label>{form.benefitKind === "COUPON" ? <label>Coupon value<input type="number" min="50" max="500" step="50" value={form.couponAmount} onChange={(e)=>setForm({...form,couponAmount:e.target.value})}/></label> : <label>Reward points<input type="number" min="50" max="500" step="50" value={form.rewardPoints} onChange={(e)=>setForm({...form,rewardPoints:e.target.value})}/></label>}<label>Validity days<input type="number" min="1" max="90" value={form.validDays} onChange={(e)=>setForm({...form,validDays:e.target.value})}/></label><label>Audience policy<select value={form.audiencePolicy} onChange={(e)=>setForm({...form,audiencePolicy:e.target.value})}><option value="ACCOUNT_PERSONALIZATION">Account personalization</option><option value="MARKETING_OPT_IN_ONLY">Marketing opt-in only</option></select></label></div><div className="phase86-builder-actions"><button className="button button-secondary" type="button" disabled={busy} onClick={runPreview}>Preview cohort</button><button className="button" type="button" disabled={busy || !preview || preview.overAudienceLimit} onClick={createDraft}>Create audited draft</button></div>{preview && <div className="phase86-preview"><div><span><small>ELIGIBLE</small><strong>{preview.eligible}</strong></span><span><small>SUPPRESSED</small><strong>{preview.suppressed}</strong></span></div>{preview.overAudienceLimit && <p className="alert warning">Audience exceeds the activation safety cap. Narrow the cohort before creating this campaign.</p>}<div className="phase86-suppression-list">{Object.entries(preview.reasonCounts || {}).map(([reason,count]) => <span key={reason}>{label(reason)} <strong>{count}</strong></span>)}</div>{preview.sample?.length > 0 && <details><summary>Eligible customer sample</summary>{preview.sample.map((r)=><p key={r.id}>{r.name} · {r.email} · score {r.riskScore} · {money(r.lifetimeSpend)}</p>)}</details>}</div>}</div>
      <div className="admin-panel phase86-campaign-list"><h3>Campaigns</h3>{campaigns.length===0 ? <p className="muted">No Phase 86 campaigns yet.</p> : campaigns.map((c)=><article key={c.id}><div><strong>{c.name}</strong><small>{label(c.segment)} · {label(c.benefitKind)} · {label(c.audiencePolicy)}</small><small>{c.previewEligible} eligible · {c.previewSuppressed} suppressed</small></div><span className={`phase86-campaign-state ${c.status.toLowerCase()}`}>{c.status}</span>{c.status === "DRAFT" && <button type="button" className="button button-secondary" disabled={busy} onClick={()=>activate(c.id,c.name)}>Activate</button>}</article>)}</div></div>
  </section>;
}
