import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/http";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const label=v=>String(v||"").replaceAll("_"," ");
export default function AdminProcurementCenter(){
  const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[preview,setPreview]=useState(null),[receiptPo,setReceiptPo]=useState(null);
  const [supplier,setSupplier]=useState({name:"",contactName:"",email:"",phone:"",defaultLeadTimeDays:14,paymentTermsDays:0,minimumOrderValue:0,isPreferred:false});
  const [offer,setOffer]=useState({supplierId:"",variantId:"",unitCost:"",minimumOrderQty:1,packSize:1,leadTimeDays:14,isPreferred:false});
  const [receipt,setReceipt]=useState({receiptKey:"",supplierInvoiceNumber:"",supplierInvoiceDate:"",notes:"",items:{}});
  async function load(){const r=await apiFetch("/admin/phase89-procurement/summary");setData(r.data);if(!offer.supplierId&&r.data.suppliers?.[0])setOffer(o=>({...o,supplierId:r.data.suppliers[0].id}));if(!offer.variantId&&r.data.variants?.[0])setOffer(o=>({...o,variantId:r.data.variants[0].id}))}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function run(fn){setBusy(true);setError("");setMessage("");try{await fn();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addSupplier(){await run(async()=>{const r=await apiFetch("/admin/phase89-procurement/suppliers",{method:"POST",body:JSON.stringify({...supplier,defaultLeadTimeDays:Number(supplier.defaultLeadTimeDays),paymentTermsDays:Number(supplier.paymentTermsDays),minimumOrderValue:Number(supplier.minimumOrderValue)})});setMessage(`Supplier ${r.data.name} created.`);setSupplier({name:"",contactName:"",email:"",phone:"",defaultLeadTimeDays:14,paymentTermsDays:0,minimumOrderValue:0,isPreferred:false})})}
  async function saveOffer(){await run(async()=>{const r=await apiFetch("/admin/phase89-procurement/offers",{method:"POST",body:JSON.stringify({...offer,unitCost:Number(offer.unitCost),minimumOrderQty:Number(offer.minimumOrderQty),packSize:Number(offer.packSize),leadTimeDays:Number(offer.leadTimeDays),isActive:true})});setMessage("Supplier SKU terms saved.");return r})}
  async function previewPlan(id){setBusy(true);setError("");try{const r=await apiFetch(`/admin/phase89-procurement/plans/${id}/recommendations`);setPreview(r.data)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function generate(id){if(!window.confirm("Generate supplier-specific purchase-order drafts from this approved demand plan? Stock will not change."))return;await run(async()=>{const r=await apiFetch(`/admin/phase89-procurement/plans/${id}/generate-purchase-orders`,{method:"POST"});setMessage(r.message);setPreview(null)})}
  async function action(id,kind){await run(async()=>{const r=await apiFetch(`/admin/phase89-procurement/purchase-orders/${id}/${kind}`,{method:"POST"});setMessage(r.message||`Purchase order ${kind} complete.`)})}
  function openReceipt(po){const items={};po.items.forEach(i=>{items[i.id]={acceptedQty:Math.max(0,Number(i.orderedQty)-Number(i.receivedQty)),rejectedQty:0,actualUnitCost:Number(i.unitCost),batchNumber:"",expiryDate:"",qualityNote:""}});setReceiptPo(po);setReceipt({receiptKey:crypto.randomUUID(),supplierInvoiceNumber:"",supplierInvoiceDate:"",notes:"",items})}
  async function postReceipt(){if(!receiptPo)return;await run(async()=>{const items=receiptPo.items.map(i=>({purchaseOrderItemId:i.id,acceptedQty:Number(receipt.items[i.id]?.acceptedQty||0),rejectedQty:Number(receipt.items[i.id]?.rejectedQty||0),actualUnitCost:Number(receipt.items[i.id]?.actualUnitCost||i.unitCost),batchNumber:receipt.items[i.id]?.batchNumber||null,expiryDate:receipt.items[i.id]?.expiryDate||null,qualityNote:receipt.items[i.id]?.qualityNote||null})).filter(x=>x.acceptedQty+x.rejectedQty>0);const r=await apiFetch(`/admin/phase89-procurement/purchase-orders/${receiptPo.id}/receive`,{method:"POST",body:JSON.stringify({receiptKey:receipt.receiptKey,supplierInvoiceNumber:receipt.supplierInvoiceNumber||null,supplierInvoiceDate:receipt.supplierInvoiceDate||null,notes:receipt.notes||null,items})});setMessage(r.message);setReceiptPo(null)})}
  const k=data?.kpis||{};const openPos=useMemo(()=>data?.purchaseOrders?.filter(p=>["DRAFT","APPROVED","SENT","PARTIALLY_RECEIVED"].includes(p.status))||[],[data]);
  return <section className="phase89-procurement"><div className="phase89-head"><div><p className="eyebrow">PHASE 89 · PROCUREMENT CONTROL</p><h2>Supplier Purchasing, PO & Goods Receipt Command Center</h2><p>Convert approved replenishment plans into auditable supplier purchase orders, compare quoted cost/lead-time/MOQ, receive goods with cost/quality variance checks, and add only accepted units to inventory.</p></div><button className="button button-secondary" onClick={()=>run(async()=>{})} disabled={busy}>Refresh</button></div>{error&&<p className="alert error">{error}</p>}{message&&<p className="alert success">{message}</p>}
  {data&&<div className="phase89-kpis"><article><span>ACTIVE SUPPLIERS</span><strong>{k.suppliers||0}</strong><small>{k.preferredSuppliers||0} preferred</small></article><article><span>OPEN PURCHASE ORDERS</span><strong>{k.openPurchaseOrders||0}</strong><small>{money(k.openPoValue)} committed</small></article><article><span>PENDING UNITS</span><strong>{k.pendingUnits||0}</strong><small>Accepted receipt still due</small></article><article className={k.overduePurchaseOrders?"danger":""}><span>OVERDUE POs</span><strong>{k.overduePurchaseOrders||0}</strong><small>Expected date + grace exceeded</small></article><article className={k.varianceReceipts?"warn":""}><span>RECEIPT VARIANCES</span><strong>{k.varianceReceipts||0}</strong><small>Cost / quality review</small></article></div>}
  <div className="phase89-grid"><div className="admin-panel"><h3>Supplier master</h3><p className="muted">Create suppliers with lead-time and payment defaults. Supplier status HOLD/INACTIVE is respected by sourcing.</p><div className="admin-field-grid two"><label>Name<input value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})}/></label><label>Contact<input value={supplier.contactName} onChange={e=>setSupplier({...supplier,contactName:e.target.value})}/></label><label>Email<input value={supplier.email} onChange={e=>setSupplier({...supplier,email:e.target.value})}/></label><label>Phone<input value={supplier.phone} onChange={e=>setSupplier({...supplier,phone:e.target.value})}/></label><label>Lead time days<input type="number" value={supplier.defaultLeadTimeDays} onChange={e=>setSupplier({...supplier,defaultLeadTimeDays:e.target.value})}/></label><label>Payment terms days<input type="number" value={supplier.paymentTermsDays} onChange={e=>setSupplier({...supplier,paymentTermsDays:e.target.value})}/></label><label>Minimum order value<input type="number" value={supplier.minimumOrderValue} onChange={e=>setSupplier({...supplier,minimumOrderValue:e.target.value})}/></label><label className="phase89-check"><input type="checkbox" checked={supplier.isPreferred} onChange={e=>setSupplier({...supplier,isPreferred:e.target.checked})}/> Preferred supplier</label></div><button className="button" disabled={busy||supplier.name.trim().length<2} onClick={addSupplier}>Create supplier</button><div className="phase89-supplier-list">{(data?.suppliers||[]).map(s=><article key={s.id}><div><strong>{s.name}</strong><small>{s.status} · {s.defaultLeadTimeDays}d lead · {s.paymentTermsDays}d terms</small></div><b>{s.variantOffers.length} SKU(s)</b></article>)}</div></div>
  <div className="admin-panel"><h3>Supplier SKU quotation</h3><p className="muted">Capture supplier-specific cost, MOQ, pack multiple and lead time. Phase 89 snapshots these values into the PO so later quote changes cannot rewrite history.</p><div className="admin-field-grid two"><label>Supplier<select value={offer.supplierId} onChange={e=>setOffer({...offer,supplierId:e.target.value})}>{(data?.suppliers||[]).filter(s=>s.status==="ACTIVE").map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Variant<select value={offer.variantId} onChange={e=>setOffer({...offer,variantId:e.target.value})}>{(data?.variants||[]).map(v=><option value={v.id} key={v.id}>{v.product.name} · {v.name} · {v.sku}</option>)}</select></label><label>Quoted unit cost<input type="number" step="0.01" value={offer.unitCost} onChange={e=>setOffer({...offer,unitCost:e.target.value})}/></label><label>MOQ<input type="number" value={offer.minimumOrderQty} onChange={e=>setOffer({...offer,minimumOrderQty:e.target.value})}/></label><label>Pack size<input type="number" value={offer.packSize} onChange={e=>setOffer({...offer,packSize:e.target.value})}/></label><label>Lead time days<input type="number" value={offer.leadTimeDays} onChange={e=>setOffer({...offer,leadTimeDays:e.target.value})}/></label><label className="phase89-check"><input type="checkbox" checked={offer.isPreferred} onChange={e=>setOffer({...offer,isPreferred:e.target.checked})}/> Preferred offer</label></div><button className="button" disabled={busy||!offer.supplierId||!offer.variantId||Number(offer.unitCost)<=0} onClick={saveOffer}>Save supplier terms</button></div></div>
  <div className="admin-panel phase89-plans"><h3>Approved replenishment plans → procurement</h3>{!(data?.plans||[]).length?<p className="muted">Approve a Phase 88 demand plan before generating purchasing.</p>:(data.plans||[]).map(p=><article key={p.id}><div><strong>{p.name}</strong><small>{p.recommendedUnits} recommended units · {money(p.recommendedPurchaseValue)} planning value · {p._count.purchaseOrders} existing PO(s)</small></div><button className="button button-secondary" onClick={()=>previewPlan(p.id)} disabled={busy}>Preview sourcing</button></article>)}</div>
  {preview&&<div className="admin-panel phase89-preview"><div className="phase89-preview-head"><div><p className="eyebrow">SUPPLIER ALLOCATION PREVIEW</p><h3>{preview.plan.name}</h3><p>{preview.coverage.covered}/{preview.coverage.items} reorder lines covered · {money(preview.coverage.purchaseValue)} estimated quoted value</p></div><button className="button" disabled={busy||preview.coverage.uncovered>0||preview.coverage.minimumOrderBlocked>0} onClick={()=>generate(preview.plan.id)}>Generate PO drafts</button></div>{preview.coverage.uncovered>0&&<p className="alert error">{preview.coverage.uncovered} reorder SKU(s) have no active supplier quotation. Add supplier terms before generating purchasing.</p>}{preview.coverage.minimumOrderBlocked>0&&<p className="alert error">{preview.coverage.minimumOrderBlocked} supplier group(s) are below that supplier's minimum order value. Adjust sourcing/terms before generating POs.</p>}<div className="phase89-table-wrap"><table><thead><tr><th>SKU</th><th>Plan qty</th><th>Supplier</th><th>Order qty</th><th>Unit cost</th><th>Lead</th><th>Quoted value</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.variantId}><td><strong>{r.productName}</strong><small>{r.variantName} · {r.sku}</small></td><td>{r.recommendedReorderQty}</td><td>{r.recommended?.supplierName||<b className="danger-text">UNSOURCED</b>}</td><td>{r.recommended?.orderQty||"—"}</td><td>{r.recommended?money(r.recommended.unitCost):"—"}</td><td>{r.recommended?`${r.recommended.leadTimeDays}d`:"—"}</td><td>{r.recommended?money(r.recommended.purchaseValue):"—"}</td></tr>)}</tbody></table></div></div>}
  <div className="admin-panel phase89-po"><h3>Purchase orders</h3>{!openPos.length?<p className="muted">No open Phase 89 purchase orders.</p>:openPos.map(po=><article key={po.id}><div className="phase89-po-top"><div><strong>{po.poNumber}</strong><small>{po.supplier.name} · {po.items.length} SKU(s) · expected {po.expectedAt?new Date(po.expectedAt).toLocaleDateString():"—"}</small></div><span className={`phase89-status ${po.status.toLowerCase()}`}>{label(po.status)}</span><b>{money(po.totalAmount)}</b></div><div className="phase89-po-lines">{po.items.map(i=><span key={i.id}>{i.variant.product.name} · {i.variant.name}: <b>{i.receivedQty}/{i.orderedQty}</b> accepted {i.rejectedQty?`· ${i.rejectedQty} rejected`:""}</span>)}</div><div className="phase89-actions">{po.status==="DRAFT"&&<button className="button" onClick={()=>action(po.id,"approve")} disabled={busy}>Approve PO</button>}{po.status==="APPROVED"&&<button className="button" onClick={()=>action(po.id,"send")} disabled={busy}>Mark sent</button>}{["SENT","PARTIALLY_RECEIVED"].includes(po.status)&&<button className="button" onClick={()=>openReceipt(po)} disabled={busy}>Receive goods</button>}{["DRAFT","APPROVED","SENT"].includes(po.status)&&!po.items.some(i=>Number(i.receivedQty)>0)&&<button className="button button-secondary" onClick={()=>action(po.id,"cancel")} disabled={busy}>Cancel</button>}</div></article>)}</div>
  {receiptPo&&<div className="admin-panel phase89-receipt"><div className="phase89-preview-head"><div><p className="eyebrow">GOODS RECEIPT</p><h3>{receiptPo.poNumber} · {receiptPo.supplier.name}</h3><p>Only accepted units will increase inventory. Rejected units remain outside sellable stock and are recorded as a quality variance.</p></div><button className="button button-secondary" onClick={()=>setReceiptPo(null)}>Close</button></div><div className="admin-field-grid two"><label>Supplier invoice<input value={receipt.supplierInvoiceNumber} onChange={e=>setReceipt({...receipt,supplierInvoiceNumber:e.target.value})}/></label><label>Invoice date<input type="date" value={receipt.supplierInvoiceDate} onChange={e=>setReceipt({...receipt,supplierInvoiceDate:e.target.value})}/></label></div><div className="phase89-receipt-lines">{receiptPo.items.map(i=>{const x=receipt.items[i.id]||{};const outstanding=Math.max(0,Number(i.orderedQty)-Number(i.receivedQty));return <article key={i.id}><div><strong>{i.variant.product.name} · {i.variant.name}</strong><small>{i.variant.sku} · outstanding {outstanding} · expected {money(i.unitCost)}</small></div><label>Accepted<input type="number" min="0" max={outstanding} value={x.acceptedQty??0} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[i.id]:{...x,acceptedQty:e.target.value}}})}/></label><label>Rejected<input type="number" min="0" value={x.rejectedQty??0} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[i.id]:{...x,rejectedQty:e.target.value}}})}/></label><label>Actual cost<input type="number" step="0.01" value={x.actualUnitCost??i.unitCost} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[i.id]:{...x,actualUnitCost:e.target.value}}})}/></label><label>Batch<input value={x.batchNumber??""} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[i.id]:{...x,batchNumber:e.target.value}}})}/></label><label>Expiry<input type="date" value={x.expiryDate??""} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[i.id]:{...x,expiryDate:e.target.value}}})}/></label><label>Quality note<input value={x.qualityNote??""} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[i.id]:{...x,qualityNote:e.target.value}}})}/></label></article>})}</div><label>Receipt notes<textarea rows="2" value={receipt.notes} onChange={e=>setReceipt({...receipt,notes:e.target.value})}/></label><button className="button" disabled={busy} onClick={postReceipt}>Post goods receipt</button></div>}
  {(data?.receipts||[]).length>0&&<div className="admin-panel phase89-history"><h3>Recent goods receipts</h3>{data.receipts.slice(0,12).map(r=><article key={r.id}><div><strong>{r.grnNumber}</strong><small>{r.purchaseOrder.poNumber} · {r.purchaseOrder.supplier.name} · {new Date(r.receivedAt).toLocaleString()}</small></div><span>{r.totalAcceptedQty} accepted · {r.totalRejectedQty} rejected</span><b className={r.varianceItemCount?"danger-text":""}>{r.varianceItemCount} variance item(s)</b></article>)}</div>}
  </section>
}
