import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/http";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const pct=v=>v==null?"—":`${Number(v).toFixed(1)}%`;
const label=v=>String(v||"").replaceAll("_"," ");
export default function AdminGrowthAnalyticsCenter(){
 const [data,setData]=useState(null),[detail,setDetail]=useState(null),[selected,setSelected]=useState(""),[error,setError]=useState("");
 useEffect(()=>{apiFetch("/admin/phase87-growth/summary").then(r=>{setData(r.data);if(r.data.campaigns?.[0])setSelected(r.data.campaigns[0].campaignId)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!selected)return;apiFetch(`/admin/phase87-growth/campaigns/${selected}`).then(r=>setDetail(r.data)).catch(e=>setError(e.message))},[selected]);
 const rows=data?.campaigns||[]; const totals=data?.totals||{}; const groups=detail?.groupMetrics||{};
 const csv=useMemo(()=>["Campaign,Segment,Experiment,Exposed,Conversions,Conversion Rate,Revenue,Incentive Cost,ROI",...rows.map(r=>[r.name,r.segment,r.experimentMode,r.exposed,r.conversions,(r.conversionRate*100).toFixed(2),r.attributedRevenue,r.incentiveCost,r.roiPercent==null?"":r.roiPercent.toFixed(2)].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n"),[rows]);
 function download(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="riseora-phase87-growth-attribution.csv";a.click();URL.revokeObjectURL(a.href)}
 return <section className="phase87-analytics"><div className="phase87-head"><div><p className="eyebrow">PHASE 87 · GROWTH ATTRIBUTION</p><h2>Campaign ROI & Experiment Analytics</h2><p>Measure direct coupon redemptions, last-touch post-exposure orders, control-group conversion, incremental lift and incentive economics.</p></div><button className="button button-secondary" type="button" onClick={download} disabled={!rows.length}>Export CSV</button></div>{error&&<p className="alert error">{error}</p>}{data&&<div className="phase87-kpis"><article><span>ATTRIBUTED REVENUE</span><strong>{money(totals.attributedRevenue)}</strong></article><article><span>CONVERSIONS</span><strong>{totals.conversions||0}</strong></article><article><span>INCENTIVE COST</span><strong>{money(totals.incentiveCost)}</strong></article><article><span>PORTFOLIO ROI</span><strong>{pct(totals.roiPercent)}</strong></article><article><span>MEASURED CAMPAIGNS</span><strong>{totals.campaignCount||0}</strong></article><article><span>BEST ROI</span><strong>{totals.bestCampaign?pct(totals.bestCampaign.roiPercent):"—"}</strong><small>{totals.bestCampaign?.name||"No measured winner yet"}</small></article></div>}
 <div className="phase87-grid"><div className="admin-panel"><h3>Campaign performance</h3>{!rows.length?<p className="muted">Activate a lifecycle campaign to begin attribution.</p>:rows.map(r=><button key={r.campaignId} className={selected===r.campaignId?"phase87-campaign-row active":"phase87-campaign-row"} onClick={()=>setSelected(r.campaignId)}><span><strong>{r.name}</strong><small>{label(r.segment)} · {label(r.experimentMode)}</small></span><span><b>{money(r.attributedRevenue)}</b><small>{r.conversions} conv · {pct(r.roiPercent)} ROI</small></span></button>)}</div>
 <div className="admin-panel phase87-detail">{!detail?<p className="muted">Select a campaign.</p>:<><div className="phase87-detail-head"><div><h3>{detail.name}</h3><p>{label(detail.segment)} · {detail.attributionWindowDays}d attribution window</p></div><strong>{pct(detail.roiPercent)} ROI</strong></div><div className="phase87-detail-kpis"><span><small>EXPOSED</small><b>{detail.exposed}</b></span><span><small>CONVERSION</small><b>{pct(detail.conversionRate*100)}</b></span><span><small>REVENUE</small><b>{money(detail.attributedRevenue)}</b></span><span><small>COST</small><b>{money(detail.incentiveCost)}</b></span><span><small>LIFT</small><b>{detail.incrementalLiftPoints==null?"No control":`${detail.incrementalLiftPoints.toFixed(1)} pp`}</b></span><span><small>INCREMENTAL REV.</small><b>{detail.incrementalRevenueEstimate==null?"—":money(detail.incrementalRevenueEstimate)}</b></span><span><small>DIRECT COUPON</small><b>{detail.directCouponConversions}</b></span></div><h4>Experiment groups</h4><div className="phase87-groups">{["CONTROL","VARIANT_A","VARIANT_B","STANDARD"].filter(g=>groups[g]?.exposed).map(g=><article key={g}><strong>{label(g)}</strong><span>{groups[g].exposed} exposed</span><span>{groups[g].conversions} conversions</span><span>{pct(groups[g].conversionRate*100)} CVR</span><span>{money(groups[g].revenue)} revenue</span></article>)}</div>{detail.conversions?.length>0&&<details className="phase87-conversions"><summary>Recent attributed orders</summary>{detail.conversions.map((c,i)=><p key={`${c.orderNumber}-${i}`}><strong>{c.orderNumber}</strong> · {money(c.revenue)} · {label(c.kind)} · {c.variantLabel||label(c.group)}</p>)}</details>}</>}</div></div></section>
}
