import { useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../api/http";
import { Icon } from "./Icons";
import BrandLogo from "./BrandLogo";
import { useStore } from "../context/StoreContext";
import { openAnalyticsPreferences, trackEvent } from "../analytics";

export default function Footer() {
  const { store } = useStore();
  const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [newsletterConsent, setNewsletterConsent] = useState(false);
  async function subscribe(event) { event.preventDefault(); setMessage(""); if (!newsletterConsent) return setMessage("Please confirm that you want optional Riseora marketing email."); try { const r = await apiFetch("/newsletter", { method: "POST", body: JSON.stringify({ email, source: "footer", consent: true }) }); setMessage(r.message); setEmail(""); setNewsletterConsent(false); trackEvent("newsletter_signup", { source: "footer" }); } catch (e) { setMessage(e.message); } }
  return <footer className="site-footer"><div className="container newsletter-band"><div><p className="phase3-eyebrow light">RISEORA NOTES</p><h2>Offers, launches & herbal rituals.</h2><p>Occasional email from Riseora. No forced analytics and no noisy inbox.</p></div><form onSubmit={subscribe}><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Your email address" aria-label="Email address" /><button>JOIN</button><label className="phase46-newsletter-consent"><input type="checkbox" checked={newsletterConsent} onChange={(e) => setNewsletterConsent(e.target.checked)} /> <span>I want optional Riseora offers, launches and herbal-care notes by email. I can unsubscribe any time.</span></label>{message && <small>{message}</small>}</form></div><div className="container footer-brand-row"><div className="footer-brand"><BrandLogo /></div><p>{store.brandTagline || "Everyday herbal care with a calmer, simpler shopping experience."}</p></div><div className="container footer-grid"><div><h3>Explore</h3><Link to="/shop">Shop all</Link><Link to="/offers">Offers</Link><Link to="/about">About Riseora</Link><Link to="/help">Help Center</Link><Link to="/contact">Contact us</Link></div><div><h3>Customer care</h3><Link to="/track-order">Track order</Link><Link to="/support">My support</Link><Link to="/policies/shipping">Shipping policy</Link><Link to="/policies/returns">Returns & refunds</Link><Link to="/policies/privacy">Privacy</Link><Link to="/privacy-center">Privacy Center</Link><Link to="/unsubscribe">Email preferences</Link><Link to="/policies/terms">Terms</Link></div><div><h3>Connect</h3>{store.supportEmail && <a href={`mailto:${store.supportEmail}`}>{store.supportEmail}</a>}{store.instagramUrl && <a href={store.instagramUrl} target="_blank" rel="noreferrer">Instagram</a>}{store.facebookUrl && <a href={store.facebookUrl} target="_blank" rel="noreferrer">Facebook</a>}{store.youtubeUrl && <a href={store.youtubeUrl} target="_blank" rel="noreferrer">YouTube</a>}</div><div className="footer-promise"><Icon name="leaf" size={24} /><div><strong>Riseora care</strong><p>Product information, pricing and availability are managed directly from the Riseora admin dashboard.</p></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {store.storeName || "Riseora Herbals"}. All rights reserved.</span><button type="button" className="footer-privacy-button" onClick={openAnalyticsPreferences}>Privacy choices</button></div></footer>;
}
